#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 117
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 79
#define ALIAS_COUNT 0
#define TOKEN_COUNT 39
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 3

enum {
  sym_comment = 1,
  anon_sym_use = 2,
  anon_sym_seq = 3,
  anon_sym_COMMA = 4,
  anon_sym_rout = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  sym_seq_name = 8,
  anon_sym_put = 9,
  anon_sym_EQ = 10,
  anon_sym_debug = 11,
  anon_sym_trans = 12,
  anon_sym_pers = 13,
  anon_sym_sub = 14,
  anon_sym_lab = 15,
  anon_sym_jump = 16,
  anon_sym_write = 17,
  anon_sym_iter = 18,
  anon_sym_enum = 19,
  anon_sym_AT = 20,
  anon_sym_count = 21,
  anon_sym_DOT_DOT = 22,
  anon_sym_PLUS = 23,
  anon_sym_DASH = 24,
  anon_sym_STAR = 25,
  anon_sym_GT = 26,
  anon_sym_LT = 27,
  anon_sym_DOT = 28,
  anon_sym_SQUOTE = 29,
  sym_string_literal = 30,
  anon_sym_LBRACE = 31,
  anon_sym_RBRACE = 32,
  sym_key_in = 33,
  sym_key_out = 34,
  sym_eos = 35,
  sym_bind = 36,
  sym_iden = 37,
  sym_number = 38,
  sym_source_file = 39,
  sym_unit = 40,
  sym_import = 41,
  sym_sequence = 42,
  sym_routine = 43,
  sym_tree = 44,
  sym_param_interface = 45,
  sym_param_def = 46,
  sym_param_name = 47,
  sym_rout_name = 48,
  sym_seq_entry = 49,
  sym_statement = 50,
  sym_put = 51,
  sym_debug = 52,
  sym_trans = 53,
  sym_pers = 54,
  sym_sub = 55,
  sym_lab = 56,
  sym_jump = 57,
  sym_write = 58,
  sym_iter = 59,
  sym_enum = 60,
  sym_count = 61,
  sym_expr = 62,
  sym_binary = 63,
  sym_paran = 64,
  sym_op = 65,
  sym_label = 66,
  sym_variable = 67,
  sym_string = 68,
  sym_string_content = 69,
  sym_string_format = 70,
  sym_open_scope = 71,
  sym_close_scope = 72,
  aux_sym_source_file_repeat1 = 73,
  aux_sym_sequence_repeat1 = 74,
  aux_sym_tree_repeat1 = 75,
  aux_sym_param_interface_repeat1 = 76,
  aux_sym_sub_repeat1 = 77,
  aux_sym_string_content_repeat1 = 78,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_use] = "use",
  [anon_sym_seq] = "seq",
  [anon_sym_COMMA] = ",",
  [anon_sym_rout] = "rout",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_seq_name] = "seq_name",
  [anon_sym_put] = "put",
  [anon_sym_EQ] = "=",
  [anon_sym_debug] = "debug",
  [anon_sym_trans] = "trans",
  [anon_sym_pers] = "pers",
  [anon_sym_sub] = "sub",
  [anon_sym_lab] = "lab",
  [anon_sym_jump] = "jump",
  [anon_sym_write] = "write",
  [anon_sym_iter] = "iter",
  [anon_sym_enum] = "enum",
  [anon_sym_AT] = "@",
  [anon_sym_count] = "count",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_DOT] = ".",
  [anon_sym_SQUOTE] = "'",
  [sym_string_literal] = "string_literal",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_key_in] = "key_in",
  [sym_key_out] = "key_out",
  [sym_eos] = "eos",
  [sym_bind] = "bind",
  [sym_iden] = "iden",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym_unit] = "unit",
  [sym_import] = "import",
  [sym_sequence] = "sequence",
  [sym_routine] = "routine",
  [sym_tree] = "tree",
  [sym_param_interface] = "param_interface",
  [sym_param_def] = "param_def",
  [sym_param_name] = "param_name",
  [sym_rout_name] = "rout_name",
  [sym_seq_entry] = "seq_entry",
  [sym_statement] = "statement",
  [sym_put] = "put",
  [sym_debug] = "debug",
  [sym_trans] = "trans",
  [sym_pers] = "pers",
  [sym_sub] = "sub",
  [sym_lab] = "lab",
  [sym_jump] = "jump",
  [sym_write] = "write",
  [sym_iter] = "iter",
  [sym_enum] = "enum",
  [sym_count] = "count",
  [sym_expr] = "expr",
  [sym_binary] = "binary",
  [sym_paran] = "paran",
  [sym_op] = "op",
  [sym_label] = "label",
  [sym_variable] = "variable",
  [sym_string] = "string",
  [sym_string_content] = "string_content",
  [sym_string_format] = "string_format",
  [sym_open_scope] = "open_scope",
  [sym_close_scope] = "close_scope",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_sequence_repeat1] = "sequence_repeat1",
  [aux_sym_tree_repeat1] = "tree_repeat1",
  [aux_sym_param_interface_repeat1] = "param_interface_repeat1",
  [aux_sym_sub_repeat1] = "sub_repeat1",
  [aux_sym_string_content_repeat1] = "string_content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_seq] = anon_sym_seq,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_rout] = anon_sym_rout,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_seq_name] = sym_seq_name,
  [anon_sym_put] = anon_sym_put,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_debug] = anon_sym_debug,
  [anon_sym_trans] = anon_sym_trans,
  [anon_sym_pers] = anon_sym_pers,
  [anon_sym_sub] = anon_sym_sub,
  [anon_sym_lab] = anon_sym_lab,
  [anon_sym_jump] = anon_sym_jump,
  [anon_sym_write] = anon_sym_write,
  [anon_sym_iter] = anon_sym_iter,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_count] = anon_sym_count,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_string_literal] = sym_string_literal,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_key_in] = sym_key_in,
  [sym_key_out] = sym_key_out,
  [sym_eos] = sym_eos,
  [sym_bind] = sym_bind,
  [sym_iden] = sym_iden,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym_unit] = sym_unit,
  [sym_import] = sym_import,
  [sym_sequence] = sym_sequence,
  [sym_routine] = sym_routine,
  [sym_tree] = sym_tree,
  [sym_param_interface] = sym_param_interface,
  [sym_param_def] = sym_param_def,
  [sym_param_name] = sym_param_name,
  [sym_rout_name] = sym_rout_name,
  [sym_seq_entry] = sym_seq_entry,
  [sym_statement] = sym_statement,
  [sym_put] = sym_put,
  [sym_debug] = sym_debug,
  [sym_trans] = sym_trans,
  [sym_pers] = sym_pers,
  [sym_sub] = sym_sub,
  [sym_lab] = sym_lab,
  [sym_jump] = sym_jump,
  [sym_write] = sym_write,
  [sym_iter] = sym_iter,
  [sym_enum] = sym_enum,
  [sym_count] = sym_count,
  [sym_expr] = sym_expr,
  [sym_binary] = sym_binary,
  [sym_paran] = sym_paran,
  [sym_op] = sym_op,
  [sym_label] = sym_label,
  [sym_variable] = sym_variable,
  [sym_string] = sym_string,
  [sym_string_content] = sym_string_content,
  [sym_string_format] = sym_string_format,
  [sym_open_scope] = sym_open_scope,
  [sym_close_scope] = sym_close_scope,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_sequence_repeat1] = aux_sym_sequence_repeat1,
  [aux_sym_tree_repeat1] = aux_sym_tree_repeat1,
  [aux_sym_param_interface_repeat1] = aux_sym_param_interface_repeat1,
  [aux_sym_sub_repeat1] = aux_sym_sub_repeat1,
  [aux_sym_string_content_repeat1] = aux_sym_string_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_seq] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rout] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_seq_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_put] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_debug] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_trans] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pers] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sub] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_lab] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_jump] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_write] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_iter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_count] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_key_in] = {
    .visible = true,
    .named = true,
  },
  [sym_key_out] = {
    .visible = true,
    .named = true,
  },
  [sym_eos] = {
    .visible = true,
    .named = true,
  },
  [sym_bind] = {
    .visible = true,
    .named = true,
  },
  [sym_iden] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_unit] = {
    .visible = true,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_routine] = {
    .visible = true,
    .named = true,
  },
  [sym_tree] = {
    .visible = true,
    .named = true,
  },
  [sym_param_interface] = {
    .visible = true,
    .named = true,
  },
  [sym_param_def] = {
    .visible = true,
    .named = true,
  },
  [sym_param_name] = {
    .visible = true,
    .named = true,
  },
  [sym_rout_name] = {
    .visible = true,
    .named = true,
  },
  [sym_seq_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_put] = {
    .visible = true,
    .named = true,
  },
  [sym_debug] = {
    .visible = true,
    .named = true,
  },
  [sym_trans] = {
    .visible = true,
    .named = true,
  },
  [sym_pers] = {
    .visible = true,
    .named = true,
  },
  [sym_sub] = {
    .visible = true,
    .named = true,
  },
  [sym_lab] = {
    .visible = true,
    .named = true,
  },
  [sym_jump] = {
    .visible = true,
    .named = true,
  },
  [sym_write] = {
    .visible = true,
    .named = true,
  },
  [sym_iter] = {
    .visible = true,
    .named = true,
  },
  [sym_enum] = {
    .visible = true,
    .named = true,
  },
  [sym_count] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binary] = {
    .visible = true,
    .named = true,
  },
  [sym_paran] = {
    .visible = true,
    .named = true,
  },
  [sym_op] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_string_format] = {
    .visible = true,
    .named = true,
  },
  [sym_open_scope] = {
    .visible = true,
    .named = true,
  },
  [sym_close_scope] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tree_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_param_interface_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sub_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_content = 1,
  field_left = 2,
  field_op = 3,
  field_right = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_left] = "left",
  [field_op] = "op",
  [field_right] = "right",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_content, 0},
  [1] =
    {field_left, 0},
    {field_op, 1},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 19,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(47);
      if (lookahead == '"') ADVANCE(46);
      if (lookahead == '\'') ADVANCE(77);
      if (lookahead == '(') ADVANCE(53);
      if (lookahead == ')') ADVANCE(54);
      if (lookahead == '*') ADVANCE(73);
      if (lookahead == '+') ADVANCE(71);
      if (lookahead == ',') ADVANCE(51);
      if (lookahead == '-') ADVANCE(72);
      if (lookahead == '.') ADVANCE(76);
      if (lookahead == ';') ADVANCE(84);
      if (lookahead == '<') ADVANCE(75);
      if (lookahead == '=') ADVANCE(58);
      if (lookahead == '>') ADVANCE(74);
      if (lookahead == '@') ADVANCE(68);
      if (lookahead == 'c') ADVANCE(24);
      if (lookahead == 'd') ADVANCE(10);
      if (lookahead == 'e') ADVANCE(23);
      if (lookahead == 'i') ADVANCE(20);
      if (lookahead == 'j') ADVANCE(40);
      if (lookahead == 'l') ADVANCE(5);
      if (lookahead == 'o') ADVANCE(41);
      if (lookahead == 'p') ADVANCE(14);
      if (lookahead == 'r') ADVANCE(25);
      if (lookahead == 's') ADVANCE(11);
      if (lookahead == 't') ADVANCE(30);
      if (lookahead == 'u') ADVANCE(34);
      if (lookahead == 'w') ADVANCE(28);
      if (lookahead == '{') ADVANCE(80);
      if (lookahead == '}') ADVANCE(81);
      if (lookahead == '~') ADVANCE(85);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(87);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(56);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(48);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(77);
      if (lookahead == '(') ADVANCE(53);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(87);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(55);
      if (lookahead == ':' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(77);
      if (lookahead == '{') ADVANCE(80);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(79);
      END_STATE();
    case 4:
      if (lookahead == ')') ADVANCE(54);
      if (lookahead == '*') ADVANCE(73);
      if (lookahead == '+') ADVANCE(71);
      if (lookahead == ',') ADVANCE(51);
      if (lookahead == '-') ADVANCE(72);
      if (lookahead == '.') ADVANCE(76);
      if (lookahead == ';') ADVANCE(84);
      if (lookahead == '<') ADVANCE(75);
      if (lookahead == '=') ADVANCE(58);
      if (lookahead == '>') ADVANCE(74);
      if (lookahead == '@') ADVANCE(68);
      if (lookahead == '{') ADVANCE(80);
      if (lookahead == '}') ADVANCE(81);
      if (lookahead == '~') ADVANCE(85);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 7:
      if (lookahead == 'b') ADVANCE(63);
      END_STATE();
    case 8:
      if (lookahead == 'b') ADVANCE(62);
      END_STATE();
    case 9:
      if (lookahead == 'b') ADVANCE(42);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(27);
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(65);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(31);
      if (lookahead == 'u') ADVANCE(36);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 16:
      if (lookahead == 'g') ADVANCE(59);
      END_STATE();
    case 17:
      if (lookahead == 'i') ADVANCE(39);
      END_STATE();
    case 18:
      if (lookahead == 'm') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 'm') ADVANCE(67);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(82);
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(44);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(43);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(45);
      END_STATE();
    case 26:
      if (lookahead == 'p') ADVANCE(64);
      END_STATE();
    case 27:
      if (lookahead == 'q') ADVANCE(50);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(66);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(6);
      END_STATE();
    case 31:
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 32:
      if (lookahead == 's') ADVANCE(61);
      END_STATE();
    case 33:
      if (lookahead == 's') ADVANCE(60);
      END_STATE();
    case 34:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(83);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(52);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(69);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 40:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 41:
      if (lookahead == 'u') ADVANCE(35);
      END_STATE();
    case 42:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 43:
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 44:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 45:
      if (lookahead == 'u') ADVANCE(37);
      END_STATE();
    case 46:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_seq);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_rout);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_seq_name);
      if (lookahead == '_') ADVANCE(86);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_seq_name);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_put);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_debug);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_trans);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_pers);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_sub);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_lab);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_jump);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_write);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_iter);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_count);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(70);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_string_literal);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(79);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_string_literal);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_key_in);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_key_out);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_eos);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_bind);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_iden);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(87);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 3},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 4},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 4},
  [79] = {.lex_state = 4},
  [80] = {.lex_state = 4},
  [81] = {.lex_state = 4},
  [82] = {.lex_state = 4},
  [83] = {.lex_state = 4},
  [84] = {.lex_state = 4},
  [85] = {.lex_state = 3},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 4},
  [88] = {.lex_state = 2},
  [89] = {.lex_state = 4},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 4},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 4},
  [94] = {.lex_state = 4},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 4},
  [99] = {.lex_state = 4},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 4},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_seq] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_rout] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_seq_name] = ACTIONS(1),
    [anon_sym_put] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_debug] = ACTIONS(1),
    [anon_sym_trans] = ACTIONS(1),
    [anon_sym_pers] = ACTIONS(1),
    [anon_sym_sub] = ACTIONS(1),
    [anon_sym_lab] = ACTIONS(1),
    [anon_sym_jump] = ACTIONS(1),
    [anon_sym_write] = ACTIONS(1),
    [anon_sym_iter] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_count] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_key_in] = ACTIONS(1),
    [sym_key_out] = ACTIONS(1),
    [sym_eos] = ACTIONS(1),
    [sym_bind] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(116),
    [sym_unit] = STATE(20),
    [sym_import] = STATE(67),
    [sym_sequence] = STATE(67),
    [sym_routine] = STATE(67),
    [aux_sym_source_file_repeat1] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [anon_sym_use] = ACTIONS(7),
    [anon_sym_seq] = ACTIONS(9),
    [anon_sym_rout] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_put,
    ACTIONS(17), 1,
      anon_sym_debug,
    ACTIONS(19), 1,
      anon_sym_trans,
    ACTIONS(21), 1,
      anon_sym_pers,
    ACTIONS(23), 1,
      anon_sym_sub,
    ACTIONS(25), 1,
      anon_sym_lab,
    ACTIONS(27), 1,
      anon_sym_jump,
    ACTIONS(29), 1,
      anon_sym_write,
    ACTIONS(31), 1,
      anon_sym_iter,
    ACTIONS(33), 1,
      anon_sym_enum,
    ACTIONS(35), 1,
      anon_sym_count,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    STATE(6), 1,
      sym_close_scope,
    STATE(3), 2,
      sym_statement,
      aux_sym_tree_repeat1,
    STATE(14), 3,
      sym_iter,
      sym_enum,
      sym_count,
    STATE(103), 8,
      sym_put,
      sym_debug,
      sym_trans,
      sym_pers,
      sym_sub,
      sym_lab,
      sym_jump,
      sym_write,
  [62] = 17,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_put,
    ACTIONS(17), 1,
      anon_sym_debug,
    ACTIONS(19), 1,
      anon_sym_trans,
    ACTIONS(21), 1,
      anon_sym_pers,
    ACTIONS(23), 1,
      anon_sym_sub,
    ACTIONS(25), 1,
      anon_sym_lab,
    ACTIONS(27), 1,
      anon_sym_jump,
    ACTIONS(29), 1,
      anon_sym_write,
    ACTIONS(31), 1,
      anon_sym_iter,
    ACTIONS(33), 1,
      anon_sym_enum,
    ACTIONS(35), 1,
      anon_sym_count,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    STATE(7), 1,
      sym_close_scope,
    STATE(4), 2,
      sym_statement,
      aux_sym_tree_repeat1,
    STATE(14), 3,
      sym_iter,
      sym_enum,
      sym_count,
    STATE(103), 8,
      sym_put,
      sym_debug,
      sym_trans,
      sym_pers,
      sym_sub,
      sym_lab,
      sym_jump,
      sym_write,
  [124] = 16,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(42), 1,
      anon_sym_put,
    ACTIONS(45), 1,
      anon_sym_debug,
    ACTIONS(48), 1,
      anon_sym_trans,
    ACTIONS(51), 1,
      anon_sym_pers,
    ACTIONS(54), 1,
      anon_sym_sub,
    ACTIONS(57), 1,
      anon_sym_lab,
    ACTIONS(60), 1,
      anon_sym_jump,
    ACTIONS(63), 1,
      anon_sym_write,
    ACTIONS(66), 1,
      anon_sym_iter,
    ACTIONS(69), 1,
      anon_sym_enum,
    ACTIONS(72), 1,
      anon_sym_count,
    ACTIONS(75), 1,
      anon_sym_RBRACE,
    STATE(4), 2,
      sym_statement,
      aux_sym_tree_repeat1,
    STATE(14), 3,
      sym_iter,
      sym_enum,
      sym_count,
    STATE(103), 8,
      sym_put,
      sym_debug,
      sym_trans,
      sym_pers,
      sym_sub,
      sym_lab,
      sym_jump,
      sym_write,
  [183] = 1,
    ACTIONS(77), 17,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_RBRACE,
  [203] = 1,
    ACTIONS(79), 17,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_RBRACE,
  [223] = 1,
    ACTIONS(81), 17,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_RBRACE,
  [243] = 2,
    ACTIONS(85), 1,
      anon_sym_DOT,
    ACTIONS(83), 15,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_AT,
      anon_sym_DOT_DOT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_eos,
      sym_bind,
      sym_iden,
  [264] = 3,
    ACTIONS(89), 1,
      anon_sym_DOT,
    STATE(33), 1,
      sym_op,
    ACTIONS(87), 14,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_AT,
      anon_sym_DOT_DOT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_eos,
      sym_bind,
      sym_iden,
  [287] = 2,
    ACTIONS(93), 1,
      anon_sym_DOT,
    ACTIONS(91), 14,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_AT,
      anon_sym_DOT_DOT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_eos,
      sym_bind,
      sym_iden,
  [307] = 2,
    ACTIONS(97), 1,
      anon_sym_DOT,
    ACTIONS(95), 14,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_AT,
      anon_sym_DOT_DOT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_eos,
      sym_bind,
      sym_iden,
  [327] = 2,
    ACTIONS(101), 1,
      anon_sym_DOT,
    ACTIONS(99), 14,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_AT,
      anon_sym_DOT_DOT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_eos,
      sym_bind,
      sym_iden,
  [347] = 2,
    ACTIONS(105), 1,
      anon_sym_DOT,
    ACTIONS(103), 14,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_AT,
      anon_sym_DOT_DOT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_eos,
      sym_bind,
      sym_iden,
  [367] = 1,
    ACTIONS(107), 13,
      sym_comment,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_RBRACE,
  [383] = 1,
    ACTIONS(109), 13,
      sym_comment,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_RBRACE,
  [399] = 1,
    ACTIONS(111), 13,
      sym_comment,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_RBRACE,
  [415] = 1,
    ACTIONS(113), 13,
      sym_comment,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_RBRACE,
  [431] = 1,
    ACTIONS(115), 13,
      sym_comment,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_RBRACE,
  [447] = 1,
    ACTIONS(117), 13,
      sym_comment,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_RBRACE,
  [463] = 7,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_use,
    ACTIONS(9), 1,
      anon_sym_seq,
    ACTIONS(11), 1,
      anon_sym_rout,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
    STATE(31), 2,
      sym_unit,
      aux_sym_source_file_repeat1,
    STATE(67), 3,
      sym_import,
      sym_sequence,
      sym_routine,
  [488] = 7,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      sym_number,
    STATE(59), 1,
      sym_expr,
    ACTIONS(123), 2,
      sym_seq_name,
      sym_iden,
    STATE(11), 2,
      sym_variable,
      sym_string,
    STATE(13), 2,
      sym_binary,
      sym_paran,
  [513] = 7,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      sym_number,
    STATE(50), 1,
      sym_expr,
    ACTIONS(123), 2,
      sym_seq_name,
      sym_iden,
    STATE(11), 2,
      sym_variable,
      sym_string,
    STATE(13), 2,
      sym_binary,
      sym_paran,
  [538] = 7,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      sym_number,
    STATE(56), 1,
      sym_expr,
    ACTIONS(123), 2,
      sym_seq_name,
      sym_iden,
    STATE(11), 2,
      sym_variable,
      sym_string,
    STATE(13), 2,
      sym_binary,
      sym_paran,
  [563] = 7,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      sym_number,
    STATE(58), 1,
      sym_expr,
    ACTIONS(123), 2,
      sym_seq_name,
      sym_iden,
    STATE(11), 2,
      sym_variable,
      sym_string,
    STATE(13), 2,
      sym_binary,
      sym_paran,
  [588] = 7,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      sym_number,
    STATE(60), 1,
      sym_expr,
    ACTIONS(123), 2,
      sym_seq_name,
      sym_iden,
    STATE(11), 2,
      sym_variable,
      sym_string,
    STATE(13), 2,
      sym_binary,
      sym_paran,
  [613] = 7,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      sym_number,
    STATE(62), 1,
      sym_expr,
    ACTIONS(123), 2,
      sym_seq_name,
      sym_iden,
    STATE(11), 2,
      sym_variable,
      sym_string,
    STATE(13), 2,
      sym_binary,
      sym_paran,
  [638] = 7,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      sym_number,
    STATE(48), 1,
      sym_expr,
    ACTIONS(123), 2,
      sym_seq_name,
      sym_iden,
    STATE(11), 2,
      sym_variable,
      sym_string,
    STATE(13), 2,
      sym_binary,
      sym_paran,
  [663] = 7,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      sym_number,
    STATE(49), 1,
      sym_expr,
    ACTIONS(123), 2,
      sym_seq_name,
      sym_iden,
    STATE(11), 2,
      sym_variable,
      sym_string,
    STATE(13), 2,
      sym_binary,
      sym_paran,
  [688] = 7,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      sym_number,
    STATE(55), 1,
      sym_expr,
    ACTIONS(123), 2,
      sym_seq_name,
      sym_iden,
    STATE(11), 2,
      sym_variable,
      sym_string,
    STATE(13), 2,
      sym_binary,
      sym_paran,
  [713] = 7,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      sym_number,
    STATE(61), 1,
      sym_expr,
    ACTIONS(123), 2,
      sym_seq_name,
      sym_iden,
    STATE(11), 2,
      sym_variable,
      sym_string,
    STATE(13), 2,
      sym_binary,
      sym_paran,
  [738] = 7,
    ACTIONS(129), 1,
      ts_builtin_sym_end,
    ACTIONS(131), 1,
      sym_comment,
    ACTIONS(134), 1,
      anon_sym_use,
    ACTIONS(137), 1,
      anon_sym_seq,
    ACTIONS(140), 1,
      anon_sym_rout,
    STATE(31), 2,
      sym_unit,
      aux_sym_source_file_repeat1,
    STATE(67), 3,
      sym_import,
      sym_sequence,
      sym_routine,
  [763] = 7,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      sym_number,
    STATE(51), 1,
      sym_expr,
    ACTIONS(123), 2,
      sym_seq_name,
      sym_iden,
    STATE(11), 2,
      sym_variable,
      sym_string,
    STATE(13), 2,
      sym_binary,
      sym_paran,
  [788] = 7,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      sym_number,
    STATE(9), 1,
      sym_expr,
    ACTIONS(123), 2,
      sym_seq_name,
      sym_iden,
    STATE(11), 2,
      sym_variable,
      sym_string,
    STATE(13), 2,
      sym_binary,
      sym_paran,
  [813] = 7,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      sym_number,
    STATE(52), 1,
      sym_expr,
    ACTIONS(123), 2,
      sym_seq_name,
      sym_iden,
    STATE(11), 2,
      sym_variable,
      sym_string,
    STATE(13), 2,
      sym_binary,
      sym_paran,
  [838] = 7,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      sym_number,
    STATE(53), 1,
      sym_expr,
    ACTIONS(123), 2,
      sym_seq_name,
      sym_iden,
    STATE(11), 2,
      sym_variable,
      sym_string,
    STATE(13), 2,
      sym_binary,
      sym_paran,
  [863] = 7,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      sym_number,
    STATE(54), 1,
      sym_expr,
    ACTIONS(123), 2,
      sym_seq_name,
      sym_iden,
    STATE(11), 2,
      sym_variable,
      sym_string,
    STATE(13), 2,
      sym_binary,
      sym_paran,
  [888] = 7,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      sym_number,
    STATE(40), 1,
      sym_expr,
    ACTIONS(123), 2,
      sym_seq_name,
      sym_iden,
    STATE(11), 2,
      sym_variable,
      sym_string,
    STATE(13), 2,
      sym_binary,
      sym_paran,
  [913] = 7,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      sym_number,
    STATE(47), 1,
      sym_expr,
    ACTIONS(123), 2,
      sym_seq_name,
      sym_iden,
    STATE(11), 2,
      sym_variable,
      sym_string,
    STATE(13), 2,
      sym_binary,
      sym_paran,
  [938] = 7,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      sym_number,
    STATE(57), 1,
      sym_expr,
    ACTIONS(123), 2,
      sym_seq_name,
      sym_iden,
    STATE(11), 2,
      sym_variable,
      sym_string,
    STATE(13), 2,
      sym_binary,
      sym_paran,
  [963] = 5,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    STATE(2), 1,
      sym_open_scope,
    STATE(16), 1,
      sym_tree,
    STATE(33), 1,
      sym_op,
    ACTIONS(143), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
  [984] = 5,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    STATE(2), 1,
      sym_open_scope,
    STATE(18), 1,
      sym_tree,
    STATE(33), 1,
      sym_op,
    ACTIONS(143), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
  [1005] = 7,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      sym_number,
    STATE(45), 1,
      sym_expr,
    ACTIONS(123), 2,
      sym_seq_name,
      sym_iden,
    STATE(11), 2,
      sym_variable,
      sym_string,
    STATE(13), 2,
      sym_binary,
      sym_paran,
  [1030] = 7,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      sym_number,
    STATE(46), 1,
      sym_expr,
    ACTIONS(123), 2,
      sym_seq_name,
      sym_iden,
    STATE(11), 2,
      sym_variable,
      sym_string,
    STATE(13), 2,
      sym_binary,
      sym_paran,
  [1055] = 7,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      sym_number,
    STATE(41), 1,
      sym_expr,
    ACTIONS(123), 2,
      sym_seq_name,
      sym_iden,
    STATE(11), 2,
      sym_variable,
      sym_string,
    STATE(13), 2,
      sym_binary,
      sym_paran,
  [1080] = 4,
    ACTIONS(147), 1,
      anon_sym_COMMA,
    STATE(33), 1,
      sym_op,
    ACTIONS(149), 2,
      anon_sym_RPAREN,
      sym_iden,
    ACTIONS(143), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
  [1099] = 5,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    STATE(2), 1,
      sym_open_scope,
    STATE(17), 1,
      sym_tree,
    STATE(33), 1,
      sym_op,
    ACTIONS(143), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
  [1120] = 3,
    ACTIONS(151), 1,
      sym_bind,
    STATE(33), 1,
      sym_op,
    ACTIONS(143), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
  [1135] = 3,
    ACTIONS(153), 1,
      anon_sym_AT,
    STATE(33), 1,
      sym_op,
    ACTIONS(143), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
  [1150] = 3,
    ACTIONS(155), 1,
      sym_bind,
    STATE(33), 1,
      sym_op,
    ACTIONS(143), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
  [1165] = 3,
    ACTIONS(157), 1,
      sym_eos,
    STATE(33), 1,
      sym_op,
    ACTIONS(143), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
  [1180] = 3,
    ACTIONS(159), 1,
      sym_eos,
    STATE(33), 1,
      sym_op,
    ACTIONS(143), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
  [1195] = 3,
    ACTIONS(161), 1,
      sym_eos,
    STATE(33), 1,
      sym_op,
    ACTIONS(143), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
  [1210] = 3,
    ACTIONS(163), 1,
      sym_eos,
    STATE(33), 1,
      sym_op,
    ACTIONS(143), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
  [1225] = 3,
    ACTIONS(165), 1,
      sym_eos,
    STATE(33), 1,
      sym_op,
    ACTIONS(143), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
  [1240] = 3,
    ACTIONS(167), 1,
      anon_sym_RPAREN,
    STATE(33), 1,
      sym_op,
    ACTIONS(143), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
  [1255] = 3,
    ACTIONS(169), 1,
      sym_bind,
    STATE(33), 1,
      sym_op,
    ACTIONS(143), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
  [1270] = 4,
    ACTIONS(171), 1,
      anon_sym_DOT_DOT,
    ACTIONS(173), 1,
      anon_sym_DOT,
    STATE(33), 1,
      sym_op,
    ACTIONS(143), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
  [1287] = 3,
    ACTIONS(175), 1,
      sym_bind,
    STATE(33), 1,
      sym_op,
    ACTIONS(143), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
  [1302] = 3,
    ACTIONS(177), 1,
      anon_sym_EQ,
    STATE(33), 1,
      sym_op,
    ACTIONS(143), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
  [1317] = 3,
    ACTIONS(179), 1,
      sym_eos,
    STATE(33), 1,
      sym_op,
    ACTIONS(143), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
  [1332] = 3,
    ACTIONS(181), 1,
      sym_eos,
    STATE(33), 1,
      sym_op,
    ACTIONS(143), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
  [1347] = 3,
    ACTIONS(183), 1,
      sym_bind,
    STATE(33), 1,
      sym_op,
    ACTIONS(143), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
  [1362] = 5,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LPAREN,
    STATE(2), 1,
      sym_open_scope,
    STATE(68), 1,
      sym_tree,
    STATE(86), 1,
      sym_param_interface,
  [1378] = 3,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
    ACTIONS(189), 2,
      sym_key_in,
      sym_key_out,
    STATE(65), 2,
      sym_param_def,
      aux_sym_param_interface_repeat1,
  [1390] = 3,
    ACTIONS(191), 1,
      anon_sym_RPAREN,
    ACTIONS(189), 2,
      sym_key_in,
      sym_key_out,
    STATE(74), 2,
      sym_param_def,
      aux_sym_param_interface_repeat1,
  [1402] = 1,
    ACTIONS(193), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
  [1410] = 1,
    ACTIONS(195), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
  [1418] = 1,
    ACTIONS(197), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
  [1426] = 2,
    ACTIONS(201), 2,
      sym_seq_name,
      sym_iden,
    ACTIONS(199), 3,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      sym_number,
  [1436] = 4,
    ACTIONS(203), 1,
      anon_sym_SQUOTE,
    ACTIONS(205), 1,
      sym_string_literal,
    ACTIONS(208), 1,
      anon_sym_LBRACE,
    STATE(70), 2,
      sym_string_format,
      aux_sym_string_content_repeat1,
  [1450] = 4,
    ACTIONS(211), 1,
      sym_string_literal,
    ACTIONS(213), 1,
      anon_sym_LBRACE,
    STATE(105), 1,
      sym_string_content,
    STATE(72), 2,
      sym_string_format,
      aux_sym_string_content_repeat1,
  [1464] = 4,
    ACTIONS(213), 1,
      anon_sym_LBRACE,
    ACTIONS(215), 1,
      anon_sym_SQUOTE,
    ACTIONS(217), 1,
      sym_string_literal,
    STATE(70), 2,
      sym_string_format,
      aux_sym_string_content_repeat1,
  [1478] = 1,
    ACTIONS(219), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
  [1486] = 3,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
    ACTIONS(223), 2,
      sym_key_in,
      sym_key_out,
    STATE(74), 2,
      sym_param_def,
      aux_sym_param_interface_repeat1,
  [1498] = 5,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    ACTIONS(226), 1,
      sym_iden,
    STATE(73), 1,
      sym_close_scope,
    STATE(83), 1,
      aux_sym_sequence_repeat1,
    STATE(84), 1,
      sym_seq_entry,
  [1514] = 1,
    ACTIONS(228), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
  [1522] = 1,
    ACTIONS(230), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
  [1530] = 5,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    ACTIONS(226), 1,
      sym_iden,
    STATE(75), 1,
      aux_sym_sequence_repeat1,
    STATE(77), 1,
      sym_close_scope,
    STATE(84), 1,
      sym_seq_entry,
  [1546] = 4,
    ACTIONS(232), 1,
      sym_eos,
    ACTIONS(234), 1,
      sym_bind,
    ACTIONS(236), 1,
      sym_iden,
    STATE(96), 1,
      sym_label,
  [1559] = 4,
    ACTIONS(238), 1,
      anon_sym_RPAREN,
    ACTIONS(240), 1,
      sym_iden,
    STATE(82), 1,
      aux_sym_sub_repeat1,
    STATE(110), 1,
      sym_param_name,
  [1572] = 4,
    ACTIONS(242), 1,
      anon_sym_RPAREN,
    ACTIONS(244), 1,
      sym_iden,
    STATE(81), 1,
      aux_sym_sub_repeat1,
    STATE(110), 1,
      sym_param_name,
  [1585] = 4,
    ACTIONS(240), 1,
      sym_iden,
    ACTIONS(247), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      aux_sym_sub_repeat1,
    STATE(110), 1,
      sym_param_name,
  [1598] = 4,
    ACTIONS(249), 1,
      anon_sym_RBRACE,
    ACTIONS(251), 1,
      sym_iden,
    STATE(83), 1,
      aux_sym_sequence_repeat1,
    STATE(84), 1,
      sym_seq_entry,
  [1611] = 2,
    ACTIONS(254), 1,
      anon_sym_COMMA,
    ACTIONS(256), 2,
      anon_sym_RBRACE,
      sym_iden,
  [1619] = 2,
    ACTIONS(260), 1,
      sym_string_literal,
    ACTIONS(258), 2,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
  [1627] = 3,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    STATE(2), 1,
      sym_open_scope,
    STATE(66), 1,
      sym_tree,
  [1637] = 1,
    ACTIONS(262), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_iden,
  [1643] = 2,
    STATE(106), 1,
      sym_variable,
    ACTIONS(123), 2,
      sym_seq_name,
      sym_iden,
  [1651] = 3,
    ACTIONS(236), 1,
      sym_iden,
    ACTIONS(264), 1,
      sym_eos,
    STATE(108), 1,
      sym_label,
  [1661] = 1,
    ACTIONS(266), 3,
      anon_sym_RPAREN,
      sym_key_in,
      sym_key_out,
  [1667] = 2,
    ACTIONS(240), 1,
      sym_iden,
    STATE(113), 1,
      sym_param_name,
  [1674] = 2,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    STATE(107), 1,
      sym_string,
  [1681] = 1,
    ACTIONS(249), 2,
      anon_sym_RBRACE,
      sym_iden,
  [1686] = 2,
    ACTIONS(268), 1,
      sym_iden,
    STATE(63), 1,
      sym_rout_name,
  [1693] = 1,
    ACTIONS(270), 2,
      sym_eos,
      sym_bind,
  [1698] = 2,
    ACTIONS(272), 1,
      sym_eos,
    ACTIONS(274), 1,
      sym_bind,
  [1705] = 1,
    ACTIONS(276), 2,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
  [1710] = 2,
    ACTIONS(268), 1,
      sym_iden,
    STATE(114), 1,
      sym_rout_name,
  [1717] = 1,
    ACTIONS(278), 2,
      anon_sym_RPAREN,
      sym_iden,
  [1722] = 2,
    ACTIONS(280), 1,
      anon_sym_LBRACE,
    STATE(78), 1,
      sym_open_scope,
  [1729] = 1,
    ACTIONS(117), 2,
      anon_sym_RBRACE,
      sym_iden,
  [1734] = 1,
    ACTIONS(282), 2,
      sym_eos,
      sym_bind,
  [1739] = 1,
    ACTIONS(284), 1,
      sym_eos,
  [1743] = 1,
    ACTIONS(286), 1,
      sym_seq_name,
  [1747] = 1,
    ACTIONS(288), 1,
      anon_sym_SQUOTE,
  [1751] = 1,
    ACTIONS(290), 1,
      anon_sym_RBRACE,
  [1755] = 1,
    ACTIONS(292), 1,
      sym_eos,
  [1759] = 1,
    ACTIONS(294), 1,
      sym_eos,
  [1763] = 1,
    ACTIONS(296), 1,
      sym_eos,
  [1767] = 1,
    ACTIONS(298), 1,
      sym_bind,
  [1771] = 1,
    ACTIONS(300), 1,
      sym_eos,
  [1775] = 1,
    ACTIONS(302), 1,
      anon_sym_LBRACE,
  [1779] = 1,
    ACTIONS(304), 1,
      sym_eos,
  [1783] = 1,
    ACTIONS(306), 1,
      anon_sym_LPAREN,
  [1787] = 1,
    ACTIONS(308), 1,
      anon_sym_LBRACE,
  [1791] = 1,
    ACTIONS(310), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 62,
  [SMALL_STATE(4)] = 124,
  [SMALL_STATE(5)] = 183,
  [SMALL_STATE(6)] = 203,
  [SMALL_STATE(7)] = 223,
  [SMALL_STATE(8)] = 243,
  [SMALL_STATE(9)] = 264,
  [SMALL_STATE(10)] = 287,
  [SMALL_STATE(11)] = 307,
  [SMALL_STATE(12)] = 327,
  [SMALL_STATE(13)] = 347,
  [SMALL_STATE(14)] = 367,
  [SMALL_STATE(15)] = 383,
  [SMALL_STATE(16)] = 399,
  [SMALL_STATE(17)] = 415,
  [SMALL_STATE(18)] = 431,
  [SMALL_STATE(19)] = 447,
  [SMALL_STATE(20)] = 463,
  [SMALL_STATE(21)] = 488,
  [SMALL_STATE(22)] = 513,
  [SMALL_STATE(23)] = 538,
  [SMALL_STATE(24)] = 563,
  [SMALL_STATE(25)] = 588,
  [SMALL_STATE(26)] = 613,
  [SMALL_STATE(27)] = 638,
  [SMALL_STATE(28)] = 663,
  [SMALL_STATE(29)] = 688,
  [SMALL_STATE(30)] = 713,
  [SMALL_STATE(31)] = 738,
  [SMALL_STATE(32)] = 763,
  [SMALL_STATE(33)] = 788,
  [SMALL_STATE(34)] = 813,
  [SMALL_STATE(35)] = 838,
  [SMALL_STATE(36)] = 863,
  [SMALL_STATE(37)] = 888,
  [SMALL_STATE(38)] = 913,
  [SMALL_STATE(39)] = 938,
  [SMALL_STATE(40)] = 963,
  [SMALL_STATE(41)] = 984,
  [SMALL_STATE(42)] = 1005,
  [SMALL_STATE(43)] = 1030,
  [SMALL_STATE(44)] = 1055,
  [SMALL_STATE(45)] = 1080,
  [SMALL_STATE(46)] = 1099,
  [SMALL_STATE(47)] = 1120,
  [SMALL_STATE(48)] = 1135,
  [SMALL_STATE(49)] = 1150,
  [SMALL_STATE(50)] = 1165,
  [SMALL_STATE(51)] = 1180,
  [SMALL_STATE(52)] = 1195,
  [SMALL_STATE(53)] = 1210,
  [SMALL_STATE(54)] = 1225,
  [SMALL_STATE(55)] = 1240,
  [SMALL_STATE(56)] = 1255,
  [SMALL_STATE(57)] = 1270,
  [SMALL_STATE(58)] = 1287,
  [SMALL_STATE(59)] = 1302,
  [SMALL_STATE(60)] = 1317,
  [SMALL_STATE(61)] = 1332,
  [SMALL_STATE(62)] = 1347,
  [SMALL_STATE(63)] = 1362,
  [SMALL_STATE(64)] = 1378,
  [SMALL_STATE(65)] = 1390,
  [SMALL_STATE(66)] = 1402,
  [SMALL_STATE(67)] = 1410,
  [SMALL_STATE(68)] = 1418,
  [SMALL_STATE(69)] = 1426,
  [SMALL_STATE(70)] = 1436,
  [SMALL_STATE(71)] = 1450,
  [SMALL_STATE(72)] = 1464,
  [SMALL_STATE(73)] = 1478,
  [SMALL_STATE(74)] = 1486,
  [SMALL_STATE(75)] = 1498,
  [SMALL_STATE(76)] = 1514,
  [SMALL_STATE(77)] = 1522,
  [SMALL_STATE(78)] = 1530,
  [SMALL_STATE(79)] = 1546,
  [SMALL_STATE(80)] = 1559,
  [SMALL_STATE(81)] = 1572,
  [SMALL_STATE(82)] = 1585,
  [SMALL_STATE(83)] = 1598,
  [SMALL_STATE(84)] = 1611,
  [SMALL_STATE(85)] = 1619,
  [SMALL_STATE(86)] = 1627,
  [SMALL_STATE(87)] = 1637,
  [SMALL_STATE(88)] = 1643,
  [SMALL_STATE(89)] = 1651,
  [SMALL_STATE(90)] = 1661,
  [SMALL_STATE(91)] = 1667,
  [SMALL_STATE(92)] = 1674,
  [SMALL_STATE(93)] = 1681,
  [SMALL_STATE(94)] = 1686,
  [SMALL_STATE(95)] = 1693,
  [SMALL_STATE(96)] = 1698,
  [SMALL_STATE(97)] = 1705,
  [SMALL_STATE(98)] = 1710,
  [SMALL_STATE(99)] = 1717,
  [SMALL_STATE(100)] = 1722,
  [SMALL_STATE(101)] = 1729,
  [SMALL_STATE(102)] = 1734,
  [SMALL_STATE(103)] = 1739,
  [SMALL_STATE(104)] = 1743,
  [SMALL_STATE(105)] = 1747,
  [SMALL_STATE(106)] = 1751,
  [SMALL_STATE(107)] = 1755,
  [SMALL_STATE(108)] = 1759,
  [SMALL_STATE(109)] = 1763,
  [SMALL_STATE(110)] = 1767,
  [SMALL_STATE(111)] = 1771,
  [SMALL_STATE(112)] = 1775,
  [SMALL_STATE(113)] = 1779,
  [SMALL_STATE(114)] = 1783,
  [SMALL_STATE(115)] = 1787,
  [SMALL_STATE(116)] = 1791,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(14),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(21),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(22),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(23),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(24),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(98),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(89),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(79),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(25),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(26),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(27),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(28),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_close_scope, 1),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tree, 2),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tree, 3),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 1),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary, 3, .production_id = 2),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary, 3, .production_id = 2),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, .production_id = 1),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1, .production_id = 1),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paran, 3),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paran, 3),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_iter, 5),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 7),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_count, 7),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_open_scope, 1),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(67),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(92),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(104),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(94),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sub_repeat1, 3),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_debug, 2),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_put, 4),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trans, 4),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pers, 4),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 4),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_write, 2),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 3),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_routine, 4),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit, 1),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_routine, 3),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_op, 1),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_op, 1),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_content_repeat1, 2),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_content_repeat1, 2), SHIFT_REPEAT(70),
  [208] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_content_repeat1, 2), SHIFT_REPEAT(88),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_content, 1),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence, 5),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_param_interface_repeat1, 2),
  [223] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_param_interface_repeat1, 2), SHIFT_REPEAT(91),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 3),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence, 4),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 1),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sub_repeat1, 2),
  [244] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sub_repeat1, 2), SHIFT_REPEAT(95),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2),
  [251] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2), SHIFT_REPEAT(87),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 1),
  [258] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_format, 3),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_format, 3),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_seq_entry, 1),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lab, 1),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_def, 3),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_name, 1),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 2),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rout_name, 1),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sub_repeat1, 4),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 1),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lab, 2),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub, 4),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub, 5),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_interface, 3),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_interface, 2),
  [310] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_snug(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
