#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 130
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 98
#define ALIAS_COUNT 0
#define TOKEN_COUNT 55
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 3

enum {
  sym_comment = 1,
  anon_sym_use = 2,
  anon_sym_seq = 3,
  anon_sym_COMMA = 4,
  anon_sym_rout = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  sym_seq_name = 8,
  anon_sym_put = 9,
  anon_sym_EQ = 10,
  anon_sym_debug = 11,
  anon_sym_trans = 12,
  anon_sym_pers = 13,
  anon_sym_sub = 14,
  anon_sym_lab = 15,
  anon_sym_jump = 16,
  anon_sym_write = 17,
  anon_sym_void = 18,
  anon_sym_iter = 19,
  anon_sym_enum = 20,
  anon_sym_AT = 21,
  anon_sym_count = 22,
  anon_sym_DOT_DOT = 23,
  anon_sym_defer = 24,
  anon_sym_PLUS = 25,
  anon_sym_DASH = 26,
  anon_sym_STAR = 27,
  anon_sym_GT = 28,
  anon_sym_LT = 29,
  anon_sym_DOT = 30,
  anon_sym_PIPE_PIPE = 31,
  anon_sym_AMP_AMP = 32,
  anon_sym_PIPE = 33,
  anon_sym_AMP = 34,
  anon_sym_GT_EQ = 35,
  anon_sym_LT_EQ = 36,
  anon_sym_EQ_EQ = 37,
  anon_sym_BANG_EQ = 38,
  anon_sym_PLUS_EQ = 39,
  anon_sym_DASH_EQ = 40,
  anon_sym_EQ_PLUS = 41,
  anon_sym_EQ_DASH = 42,
  anon_sym_SQUOTE = 43,
  sym_string_literal = 44,
  anon_sym_LBRACE = 45,
  anon_sym_BQUOTE = 46,
  anon_sym_RBRACE = 47,
  sym_char_literal = 48,
  sym_key_in = 49,
  sym_key_out = 50,
  sym_eos = 51,
  sym_bind = 52,
  sym_iden = 53,
  sym_number = 54,
  sym_source_file = 55,
  sym_unit = 56,
  sym_import = 57,
  sym_sequence = 58,
  sym_routine = 59,
  sym_tree = 60,
  sym_param_interface = 61,
  sym_param_def = 62,
  sym_param_name = 63,
  sym_rout_name = 64,
  sym_seq_entry = 65,
  sym_statement = 66,
  sym_put = 67,
  sym_debug = 68,
  sym_trans = 69,
  sym_pers = 70,
  sym_sub = 71,
  sym_lab = 72,
  sym_jump = 73,
  sym_write = 74,
  sym_void = 75,
  sym_iter = 76,
  sym_enum = 77,
  sym_count = 78,
  sym_defer = 79,
  sym_expr = 80,
  sym_binary = 81,
  sym_paran = 82,
  sym_op = 83,
  sym_label = 84,
  sym_variable = 85,
  sym_string = 86,
  sym_string_content = 87,
  sym_string_format = 88,
  sym_string_format_content = 89,
  sym_open_scope = 90,
  sym_close_scope = 91,
  aux_sym_source_file_repeat1 = 92,
  aux_sym_sequence_repeat1 = 93,
  aux_sym_tree_repeat1 = 94,
  aux_sym_param_interface_repeat1 = 95,
  aux_sym_sub_repeat1 = 96,
  aux_sym_string_content_repeat1 = 97,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_use] = "use",
  [anon_sym_seq] = "seq",
  [anon_sym_COMMA] = ",",
  [anon_sym_rout] = "rout",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_seq_name] = "seq_name",
  [anon_sym_put] = "put",
  [anon_sym_EQ] = "=",
  [anon_sym_debug] = "debug",
  [anon_sym_trans] = "trans",
  [anon_sym_pers] = "pers",
  [anon_sym_sub] = "sub",
  [anon_sym_lab] = "lab",
  [anon_sym_jump] = "jump",
  [anon_sym_write] = "write",
  [anon_sym_void] = "void",
  [anon_sym_iter] = "iter",
  [anon_sym_enum] = "enum",
  [anon_sym_AT] = "@",
  [anon_sym_count] = "count",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_defer] = "defer",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_DOT] = ".",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE] = "|",
  [anon_sym_AMP] = "&",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_PLUS_EQ] = "+=",
  [anon_sym_DASH_EQ] = "-=",
  [anon_sym_EQ_PLUS] = "=+",
  [anon_sym_EQ_DASH] = "=-",
  [anon_sym_SQUOTE] = "'",
  [sym_string_literal] = "string_literal",
  [anon_sym_LBRACE] = "{",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_RBRACE] = "}",
  [sym_char_literal] = "char_literal",
  [sym_key_in] = "key_in",
  [sym_key_out] = "key_out",
  [sym_eos] = "eos",
  [sym_bind] = "bind",
  [sym_iden] = "iden",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym_unit] = "unit",
  [sym_import] = "import",
  [sym_sequence] = "sequence",
  [sym_routine] = "routine",
  [sym_tree] = "tree",
  [sym_param_interface] = "param_interface",
  [sym_param_def] = "param_def",
  [sym_param_name] = "param_name",
  [sym_rout_name] = "rout_name",
  [sym_seq_entry] = "seq_entry",
  [sym_statement] = "statement",
  [sym_put] = "put",
  [sym_debug] = "debug",
  [sym_trans] = "trans",
  [sym_pers] = "pers",
  [sym_sub] = "sub",
  [sym_lab] = "lab",
  [sym_jump] = "jump",
  [sym_write] = "write",
  [sym_void] = "void",
  [sym_iter] = "iter",
  [sym_enum] = "enum",
  [sym_count] = "count",
  [sym_defer] = "defer",
  [sym_expr] = "expr",
  [sym_binary] = "binary",
  [sym_paran] = "paran",
  [sym_op] = "op",
  [sym_label] = "label",
  [sym_variable] = "variable",
  [sym_string] = "string",
  [sym_string_content] = "string_content",
  [sym_string_format] = "string_format",
  [sym_string_format_content] = "string_format_content",
  [sym_open_scope] = "open_scope",
  [sym_close_scope] = "close_scope",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_sequence_repeat1] = "sequence_repeat1",
  [aux_sym_tree_repeat1] = "tree_repeat1",
  [aux_sym_param_interface_repeat1] = "param_interface_repeat1",
  [aux_sym_sub_repeat1] = "sub_repeat1",
  [aux_sym_string_content_repeat1] = "string_content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_seq] = anon_sym_seq,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_rout] = anon_sym_rout,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_seq_name] = sym_seq_name,
  [anon_sym_put] = anon_sym_put,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_debug] = anon_sym_debug,
  [anon_sym_trans] = anon_sym_trans,
  [anon_sym_pers] = anon_sym_pers,
  [anon_sym_sub] = anon_sym_sub,
  [anon_sym_lab] = anon_sym_lab,
  [anon_sym_jump] = anon_sym_jump,
  [anon_sym_write] = anon_sym_write,
  [anon_sym_void] = anon_sym_void,
  [anon_sym_iter] = anon_sym_iter,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_count] = anon_sym_count,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_defer] = anon_sym_defer,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_PLUS_EQ] = anon_sym_PLUS_EQ,
  [anon_sym_DASH_EQ] = anon_sym_DASH_EQ,
  [anon_sym_EQ_PLUS] = anon_sym_EQ_PLUS,
  [anon_sym_EQ_DASH] = anon_sym_EQ_DASH,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_string_literal] = sym_string_literal,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_char_literal] = sym_char_literal,
  [sym_key_in] = sym_key_in,
  [sym_key_out] = sym_key_out,
  [sym_eos] = sym_eos,
  [sym_bind] = sym_bind,
  [sym_iden] = sym_iden,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym_unit] = sym_unit,
  [sym_import] = sym_import,
  [sym_sequence] = sym_sequence,
  [sym_routine] = sym_routine,
  [sym_tree] = sym_tree,
  [sym_param_interface] = sym_param_interface,
  [sym_param_def] = sym_param_def,
  [sym_param_name] = sym_param_name,
  [sym_rout_name] = sym_rout_name,
  [sym_seq_entry] = sym_seq_entry,
  [sym_statement] = sym_statement,
  [sym_put] = sym_put,
  [sym_debug] = sym_debug,
  [sym_trans] = sym_trans,
  [sym_pers] = sym_pers,
  [sym_sub] = sym_sub,
  [sym_lab] = sym_lab,
  [sym_jump] = sym_jump,
  [sym_write] = sym_write,
  [sym_void] = sym_void,
  [sym_iter] = sym_iter,
  [sym_enum] = sym_enum,
  [sym_count] = sym_count,
  [sym_defer] = sym_defer,
  [sym_expr] = sym_expr,
  [sym_binary] = sym_binary,
  [sym_paran] = sym_paran,
  [sym_op] = sym_op,
  [sym_label] = sym_label,
  [sym_variable] = sym_variable,
  [sym_string] = sym_string,
  [sym_string_content] = sym_string_content,
  [sym_string_format] = sym_string_format,
  [sym_string_format_content] = sym_string_format_content,
  [sym_open_scope] = sym_open_scope,
  [sym_close_scope] = sym_close_scope,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_sequence_repeat1] = aux_sym_sequence_repeat1,
  [aux_sym_tree_repeat1] = aux_sym_tree_repeat1,
  [aux_sym_param_interface_repeat1] = aux_sym_param_interface_repeat1,
  [aux_sym_sub_repeat1] = aux_sym_sub_repeat1,
  [aux_sym_string_content_repeat1] = aux_sym_string_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_seq] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rout] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_seq_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_put] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_debug] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_trans] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pers] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sub] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_lab] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_jump] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_write] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_void] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_iter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_count] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_defer] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_char_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_key_in] = {
    .visible = true,
    .named = true,
  },
  [sym_key_out] = {
    .visible = true,
    .named = true,
  },
  [sym_eos] = {
    .visible = true,
    .named = true,
  },
  [sym_bind] = {
    .visible = true,
    .named = true,
  },
  [sym_iden] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_unit] = {
    .visible = true,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_routine] = {
    .visible = true,
    .named = true,
  },
  [sym_tree] = {
    .visible = true,
    .named = true,
  },
  [sym_param_interface] = {
    .visible = true,
    .named = true,
  },
  [sym_param_def] = {
    .visible = true,
    .named = true,
  },
  [sym_param_name] = {
    .visible = true,
    .named = true,
  },
  [sym_rout_name] = {
    .visible = true,
    .named = true,
  },
  [sym_seq_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_put] = {
    .visible = true,
    .named = true,
  },
  [sym_debug] = {
    .visible = true,
    .named = true,
  },
  [sym_trans] = {
    .visible = true,
    .named = true,
  },
  [sym_pers] = {
    .visible = true,
    .named = true,
  },
  [sym_sub] = {
    .visible = true,
    .named = true,
  },
  [sym_lab] = {
    .visible = true,
    .named = true,
  },
  [sym_jump] = {
    .visible = true,
    .named = true,
  },
  [sym_write] = {
    .visible = true,
    .named = true,
  },
  [sym_void] = {
    .visible = true,
    .named = true,
  },
  [sym_iter] = {
    .visible = true,
    .named = true,
  },
  [sym_enum] = {
    .visible = true,
    .named = true,
  },
  [sym_count] = {
    .visible = true,
    .named = true,
  },
  [sym_defer] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binary] = {
    .visible = true,
    .named = true,
  },
  [sym_paran] = {
    .visible = true,
    .named = true,
  },
  [sym_op] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_string_format] = {
    .visible = true,
    .named = true,
  },
  [sym_string_format_content] = {
    .visible = true,
    .named = true,
  },
  [sym_open_scope] = {
    .visible = true,
    .named = true,
  },
  [sym_close_scope] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tree_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_param_interface_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sub_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_content = 1,
  field_left = 2,
  field_op = 3,
  field_right = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_left] = "left",
  [field_op] = "op",
  [field_right] = "right",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_content, 0},
  [1] =
    {field_left, 0},
    {field_op, 1},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 37,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(54);
      if (lookahead == '!') ADVANCE(5);
      if (lookahead == '"') ADVANCE(52);
      if (lookahead == '&') ADVANCE(89);
      if (lookahead == '\'') ADVANCE(98);
      if (lookahead == '(') ADVANCE(60);
      if (lookahead == ')') ADVANCE(61);
      if (lookahead == '*') ADVANCE(82);
      if (lookahead == '+') ADVANCE(80);
      if (lookahead == ',') ADVANCE(58);
      if (lookahead == '-') ADVANCE(81);
      if (lookahead == '.') ADVANCE(85);
      if (lookahead == ';') ADVANCE(107);
      if (lookahead == '<') ADVANCE(84);
      if (lookahead == '=') ADVANCE(65);
      if (lookahead == '>') ADVANCE(83);
      if (lookahead == '@') ADVANCE(76);
      if (lookahead == '`') ADVANCE(102);
      if (lookahead == 'c') ADVANCE(29);
      if (lookahead == 'd') ADVANCE(12);
      if (lookahead == 'e') ADVANCE(27);
      if (lookahead == 'i') ADVANCE(24);
      if (lookahead == 'j') ADVANCE(46);
      if (lookahead == 'l') ADVANCE(6);
      if (lookahead == 'o') ADVANCE(47);
      if (lookahead == 'p') ADVANCE(16);
      if (lookahead == 'r') ADVANCE(30);
      if (lookahead == 's') ADVANCE(13);
      if (lookahead == 't') ADVANCE(35);
      if (lookahead == 'u') ADVANCE(40);
      if (lookahead == 'v') ADVANCE(28);
      if (lookahead == 'w') ADVANCE(37);
      if (lookahead == '{') ADVANCE(101);
      if (lookahead == '|') ADVANCE(88);
      if (lookahead == '}') ADVANCE(103);
      if (lookahead == '~') ADVANCE(108);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(110);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(63);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(55);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(5);
      if (lookahead == '"') ADVANCE(52);
      if (lookahead == '&') ADVANCE(89);
      if (lookahead == ')') ADVANCE(61);
      if (lookahead == '*') ADVANCE(82);
      if (lookahead == '+') ADVANCE(80);
      if (lookahead == ',') ADVANCE(58);
      if (lookahead == '-') ADVANCE(81);
      if (lookahead == '.') ADVANCE(85);
      if (lookahead == ';') ADVANCE(107);
      if (lookahead == '<') ADVANCE(84);
      if (lookahead == '=') ADVANCE(65);
      if (lookahead == '>') ADVANCE(83);
      if (lookahead == '@') ADVANCE(76);
      if (lookahead == '`') ADVANCE(102);
      if (lookahead == '{') ADVANCE(101);
      if (lookahead == '|') ADVANCE(88);
      if (lookahead == '}') ADVANCE(103);
      if (lookahead == '~') ADVANCE(108);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(98);
      if (lookahead == '(') ADVANCE(60);
      if (lookahead == '`') ADVANCE(53);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(110);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(62);
      if (lookahead == ':' ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(98);
      if (lookahead == '{') ADVANCE(101);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(99);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(100);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(93);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 8:
      if (lookahead == 'b') ADVANCE(70);
      END_STATE();
    case 9:
      if (lookahead == 'b') ADVANCE(69);
      END_STATE();
    case 10:
      if (lookahead == 'b') ADVANCE(48);
      if (lookahead == 'f') ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(73);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(32);
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(56);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(36);
      if (lookahead == 'u') ADVANCE(42);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 19:
      if (lookahead == 'g') ADVANCE(66);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(11);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(45);
      END_STATE();
    case 22:
      if (lookahead == 'm') ADVANCE(31);
      END_STATE();
    case 23:
      if (lookahead == 'm') ADVANCE(75);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(105);
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(39);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(44);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(50);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 29:
      if (lookahead == 'o') ADVANCE(49);
      END_STATE();
    case 30:
      if (lookahead == 'o') ADVANCE(51);
      END_STATE();
    case 31:
      if (lookahead == 'p') ADVANCE(71);
      END_STATE();
    case 32:
      if (lookahead == 'q') ADVANCE(57);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(74);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(79);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 36:
      if (lookahead == 'r') ADVANCE(38);
      END_STATE();
    case 37:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 38:
      if (lookahead == 's') ADVANCE(68);
      END_STATE();
    case 39:
      if (lookahead == 's') ADVANCE(67);
      END_STATE();
    case 40:
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 41:
      if (lookahead == 't') ADVANCE(106);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(64);
      END_STATE();
    case 43:
      if (lookahead == 't') ADVANCE(59);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(77);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 46:
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 47:
      if (lookahead == 'u') ADVANCE(41);
      END_STATE();
    case 48:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 49:
      if (lookahead == 'u') ADVANCE(26);
      END_STATE();
    case 50:
      if (lookahead == 'u') ADVANCE(23);
      END_STATE();
    case 51:
      if (lookahead == 'u') ADVANCE(43);
      END_STATE();
    case 52:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 53:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(104);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_seq);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_rout);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_seq_name);
      if (lookahead == '_') ADVANCE(109);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_seq_name);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_put);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '+') ADVANCE(96);
      if (lookahead == '-') ADVANCE(97);
      if (lookahead == '=') ADVANCE(92);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_debug);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_trans);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_pers);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_sub);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_lab);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_jump);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_write);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_void);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_iter);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_count);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_defer);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '=') ADVANCE(94);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '=') ADVANCE(95);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(90);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(91);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(78);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '|') ADVANCE(86);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == '&') ADVANCE(87);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_PLUS_EQ);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_DASH_EQ);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_EQ_PLUS);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_EQ_DASH);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_string_literal);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(99);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(100);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_string_literal);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(100);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_char_literal);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_key_in);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_key_out);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_eos);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_bind);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_iden);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(110);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 4},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 4},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 4},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 2},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 2},
  [85] = {.lex_state = 2},
  [86] = {.lex_state = 2},
  [87] = {.lex_state = 2},
  [88] = {.lex_state = 2},
  [89] = {.lex_state = 2},
  [90] = {.lex_state = 2},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 2},
  [93] = {.lex_state = 4},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 2},
  [97] = {.lex_state = 2},
  [98] = {.lex_state = 4},
  [99] = {.lex_state = 2},
  [100] = {.lex_state = 2},
  [101] = {.lex_state = 2},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 2},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 2},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 2},
  [110] = {.lex_state = 2},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 2},
  [113] = {.lex_state = 2},
  [114] = {.lex_state = 2},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_seq] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_rout] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_seq_name] = ACTIONS(1),
    [anon_sym_put] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_debug] = ACTIONS(1),
    [anon_sym_trans] = ACTIONS(1),
    [anon_sym_pers] = ACTIONS(1),
    [anon_sym_sub] = ACTIONS(1),
    [anon_sym_lab] = ACTIONS(1),
    [anon_sym_jump] = ACTIONS(1),
    [anon_sym_write] = ACTIONS(1),
    [anon_sym_void] = ACTIONS(1),
    [anon_sym_iter] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_count] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_defer] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_PLUS_EQ] = ACTIONS(1),
    [anon_sym_DASH_EQ] = ACTIONS(1),
    [anon_sym_EQ_PLUS] = ACTIONS(1),
    [anon_sym_EQ_DASH] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_key_in] = ACTIONS(1),
    [sym_key_out] = ACTIONS(1),
    [sym_eos] = ACTIONS(1),
    [sym_bind] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(116),
    [sym_unit] = STATE(66),
    [sym_import] = STATE(70),
    [sym_sequence] = STATE(70),
    [sym_routine] = STATE(70),
    [aux_sym_source_file_repeat1] = STATE(66),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [anon_sym_use] = ACTIONS(7),
    [anon_sym_seq] = ACTIONS(9),
    [anon_sym_rout] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 19,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_put,
    ACTIONS(17), 1,
      anon_sym_debug,
    ACTIONS(19), 1,
      anon_sym_trans,
    ACTIONS(21), 1,
      anon_sym_pers,
    ACTIONS(23), 1,
      anon_sym_sub,
    ACTIONS(25), 1,
      anon_sym_lab,
    ACTIONS(27), 1,
      anon_sym_jump,
    ACTIONS(29), 1,
      anon_sym_write,
    ACTIONS(31), 1,
      anon_sym_void,
    ACTIONS(33), 1,
      anon_sym_iter,
    ACTIONS(35), 1,
      anon_sym_enum,
    ACTIONS(37), 1,
      anon_sym_count,
    ACTIONS(39), 1,
      anon_sym_defer,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    STATE(35), 1,
      sym_close_scope,
    STATE(4), 2,
      sym_statement,
      aux_sym_tree_repeat1,
    STATE(36), 4,
      sym_iter,
      sym_enum,
      sym_count,
      sym_defer,
    STATE(118), 9,
      sym_put,
      sym_debug,
      sym_trans,
      sym_pers,
      sym_sub,
      sym_lab,
      sym_jump,
      sym_write,
      sym_void,
  [70] = 19,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_put,
    ACTIONS(17), 1,
      anon_sym_debug,
    ACTIONS(19), 1,
      anon_sym_trans,
    ACTIONS(21), 1,
      anon_sym_pers,
    ACTIONS(23), 1,
      anon_sym_sub,
    ACTIONS(25), 1,
      anon_sym_lab,
    ACTIONS(27), 1,
      anon_sym_jump,
    ACTIONS(29), 1,
      anon_sym_write,
    ACTIONS(31), 1,
      anon_sym_void,
    ACTIONS(33), 1,
      anon_sym_iter,
    ACTIONS(35), 1,
      anon_sym_enum,
    ACTIONS(37), 1,
      anon_sym_count,
    ACTIONS(39), 1,
      anon_sym_defer,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    STATE(33), 1,
      sym_close_scope,
    STATE(2), 2,
      sym_statement,
      aux_sym_tree_repeat1,
    STATE(36), 4,
      sym_iter,
      sym_enum,
      sym_count,
      sym_defer,
    STATE(118), 9,
      sym_put,
      sym_debug,
      sym_trans,
      sym_pers,
      sym_sub,
      sym_lab,
      sym_jump,
      sym_write,
      sym_void,
  [140] = 18,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_put,
    ACTIONS(49), 1,
      anon_sym_debug,
    ACTIONS(52), 1,
      anon_sym_trans,
    ACTIONS(55), 1,
      anon_sym_pers,
    ACTIONS(58), 1,
      anon_sym_sub,
    ACTIONS(61), 1,
      anon_sym_lab,
    ACTIONS(64), 1,
      anon_sym_jump,
    ACTIONS(67), 1,
      anon_sym_write,
    ACTIONS(70), 1,
      anon_sym_void,
    ACTIONS(73), 1,
      anon_sym_iter,
    ACTIONS(76), 1,
      anon_sym_enum,
    ACTIONS(79), 1,
      anon_sym_count,
    ACTIONS(82), 1,
      anon_sym_defer,
    ACTIONS(85), 1,
      anon_sym_RBRACE,
    STATE(4), 2,
      sym_statement,
      aux_sym_tree_repeat1,
    STATE(36), 4,
      sym_iter,
      sym_enum,
      sym_count,
      sym_defer,
    STATE(118), 9,
      sym_put,
      sym_debug,
      sym_trans,
      sym_pers,
      sym_sub,
      sym_lab,
      sym_jump,
      sym_write,
      sym_void,
  [207] = 3,
    STATE(43), 1,
      sym_op,
    ACTIONS(89), 8,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(87), 19,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AT,
      anon_sym_DOT_DOT,
      anon_sym_STAR,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
      anon_sym_LBRACE,
      sym_eos,
      sym_bind,
      sym_iden,
  [242] = 17,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_put,
    ACTIONS(17), 1,
      anon_sym_debug,
    ACTIONS(19), 1,
      anon_sym_trans,
    ACTIONS(21), 1,
      anon_sym_pers,
    ACTIONS(23), 1,
      anon_sym_sub,
    ACTIONS(25), 1,
      anon_sym_lab,
    ACTIONS(27), 1,
      anon_sym_jump,
    ACTIONS(29), 1,
      anon_sym_write,
    ACTIONS(31), 1,
      anon_sym_void,
    ACTIONS(33), 1,
      anon_sym_iter,
    ACTIONS(35), 1,
      anon_sym_enum,
    ACTIONS(37), 1,
      anon_sym_count,
    ACTIONS(39), 1,
      anon_sym_defer,
    STATE(38), 1,
      sym_statement,
    STATE(36), 4,
      sym_iter,
      sym_enum,
      sym_count,
      sym_defer,
    STATE(118), 9,
      sym_put,
      sym_debug,
      sym_trans,
      sym_pers,
      sym_sub,
      sym_lab,
      sym_jump,
      sym_write,
      sym_void,
  [305] = 2,
    ACTIONS(93), 8,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(91), 20,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AT,
      anon_sym_DOT_DOT,
      anon_sym_STAR,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_eos,
      sym_bind,
      sym_iden,
  [338] = 2,
    ACTIONS(97), 8,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(95), 19,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AT,
      anon_sym_DOT_DOT,
      anon_sym_STAR,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
      anon_sym_LBRACE,
      sym_eos,
      sym_bind,
      sym_iden,
  [370] = 2,
    ACTIONS(101), 8,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(99), 19,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AT,
      anon_sym_DOT_DOT,
      anon_sym_STAR,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
      anon_sym_LBRACE,
      sym_eos,
      sym_bind,
      sym_iden,
  [402] = 2,
    ACTIONS(105), 8,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(103), 19,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AT,
      anon_sym_DOT_DOT,
      anon_sym_STAR,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
      anon_sym_LBRACE,
      sym_eos,
      sym_bind,
      sym_iden,
  [434] = 2,
    ACTIONS(109), 8,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(107), 19,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AT,
      anon_sym_DOT_DOT,
      anon_sym_STAR,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
      anon_sym_LBRACE,
      sym_eos,
      sym_bind,
      sym_iden,
  [466] = 6,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    STATE(3), 1,
      sym_open_scope,
    STATE(42), 1,
      sym_tree,
    STATE(43), 1,
      sym_op,
    ACTIONS(111), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(113), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [501] = 6,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    STATE(3), 1,
      sym_open_scope,
    STATE(40), 1,
      sym_tree,
    STATE(43), 1,
      sym_op,
    ACTIONS(111), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(113), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [536] = 5,
    ACTIONS(117), 1,
      anon_sym_COMMA,
    STATE(43), 1,
      sym_op,
    ACTIONS(119), 2,
      anon_sym_RPAREN,
      sym_iden,
    ACTIONS(111), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(113), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [569] = 6,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    STATE(3), 1,
      sym_open_scope,
    STATE(41), 1,
      sym_tree,
    STATE(43), 1,
      sym_op,
    ACTIONS(111), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(113), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [604] = 4,
    ACTIONS(121), 1,
      sym_bind,
    STATE(43), 1,
      sym_op,
    ACTIONS(111), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(113), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [633] = 4,
    ACTIONS(123), 1,
      sym_bind,
    STATE(43), 1,
      sym_op,
    ACTIONS(111), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(113), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [662] = 4,
    ACTIONS(125), 1,
      sym_bind,
    STATE(43), 1,
      sym_op,
    ACTIONS(111), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(113), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [691] = 4,
    ACTIONS(127), 1,
      sym_eos,
    STATE(43), 1,
      sym_op,
    ACTIONS(111), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(113), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [720] = 4,
    ACTIONS(129), 1,
      sym_bind,
    STATE(43), 1,
      sym_op,
    ACTIONS(111), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(113), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [749] = 4,
    ACTIONS(131), 1,
      anon_sym_EQ,
    STATE(43), 1,
      sym_op,
    ACTIONS(111), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(113), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [778] = 4,
    ACTIONS(133), 1,
      sym_eos,
    STATE(43), 1,
      sym_op,
    ACTIONS(111), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(113), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [807] = 4,
    ACTIONS(135), 1,
      sym_bind,
    STATE(43), 1,
      sym_op,
    ACTIONS(111), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(113), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [836] = 4,
    ACTIONS(137), 1,
      sym_eos,
    STATE(43), 1,
      sym_op,
    ACTIONS(111), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(113), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [865] = 4,
    ACTIONS(139), 1,
      anon_sym_AT,
    STATE(43), 1,
      sym_op,
    ACTIONS(111), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(113), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [894] = 4,
    ACTIONS(141), 1,
      sym_eos,
    STATE(43), 1,
      sym_op,
    ACTIONS(111), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(113), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [923] = 4,
    ACTIONS(143), 1,
      sym_eos,
    STATE(43), 1,
      sym_op,
    ACTIONS(111), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(113), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [952] = 4,
    ACTIONS(145), 1,
      anon_sym_DOT_DOT,
    STATE(43), 1,
      sym_op,
    ACTIONS(111), 7,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(113), 11,
      anon_sym_STAR,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [981] = 4,
    ACTIONS(147), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      sym_op,
    ACTIONS(111), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(113), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [1010] = 4,
    ACTIONS(149), 1,
      sym_eos,
    STATE(43), 1,
      sym_op,
    ACTIONS(111), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(113), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [1039] = 4,
    ACTIONS(151), 1,
      sym_eos,
    STATE(43), 1,
      sym_op,
    ACTIONS(111), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(113), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [1068] = 4,
    ACTIONS(153), 1,
      sym_eos,
    STATE(43), 1,
      sym_op,
    ACTIONS(111), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(113), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [1097] = 1,
    ACTIONS(155), 19,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_void,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_defer,
      anon_sym_RBRACE,
  [1119] = 1,
    ACTIONS(157), 19,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_void,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_defer,
      anon_sym_RBRACE,
  [1141] = 1,
    ACTIONS(159), 19,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_void,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_defer,
      anon_sym_RBRACE,
  [1163] = 1,
    ACTIONS(161), 15,
      sym_comment,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_void,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_defer,
      anon_sym_RBRACE,
  [1181] = 1,
    ACTIONS(163), 15,
      sym_comment,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_void,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_defer,
      anon_sym_RBRACE,
  [1199] = 1,
    ACTIONS(165), 15,
      sym_comment,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_void,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_defer,
      anon_sym_RBRACE,
  [1217] = 1,
    ACTIONS(167), 15,
      sym_comment,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_void,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_defer,
      anon_sym_RBRACE,
  [1235] = 1,
    ACTIONS(169), 15,
      sym_comment,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_void,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_defer,
      anon_sym_RBRACE,
  [1253] = 1,
    ACTIONS(171), 15,
      sym_comment,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_void,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_defer,
      anon_sym_RBRACE,
  [1271] = 1,
    ACTIONS(173), 15,
      sym_comment,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_void,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_defer,
      anon_sym_RBRACE,
  [1289] = 8,
    ACTIONS(175), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 1,
      sym_seq_name,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      sym_iden,
    STATE(5), 1,
      sym_expr,
    ACTIONS(181), 2,
      sym_char_literal,
      sym_number,
    STATE(9), 2,
      sym_binary,
      sym_paran,
    STATE(10), 2,
      sym_variable,
      sym_string,
  [1317] = 8,
    ACTIONS(175), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 1,
      sym_seq_name,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      sym_iden,
    STATE(16), 1,
      sym_expr,
    ACTIONS(181), 2,
      sym_char_literal,
      sym_number,
    STATE(9), 2,
      sym_binary,
      sym_paran,
    STATE(10), 2,
      sym_variable,
      sym_string,
  [1345] = 8,
    ACTIONS(175), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 1,
      sym_seq_name,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      sym_iden,
    STATE(32), 1,
      sym_expr,
    ACTIONS(181), 2,
      sym_char_literal,
      sym_number,
    STATE(9), 2,
      sym_binary,
      sym_paran,
    STATE(10), 2,
      sym_variable,
      sym_string,
  [1373] = 8,
    ACTIONS(175), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 1,
      sym_seq_name,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      sym_iden,
    STATE(13), 1,
      sym_expr,
    ACTIONS(181), 2,
      sym_char_literal,
      sym_number,
    STATE(9), 2,
      sym_binary,
      sym_paran,
    STATE(10), 2,
      sym_variable,
      sym_string,
  [1401] = 8,
    ACTIONS(175), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 1,
      sym_seq_name,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      sym_iden,
    STATE(22), 1,
      sym_expr,
    ACTIONS(181), 2,
      sym_char_literal,
      sym_number,
    STATE(9), 2,
      sym_binary,
      sym_paran,
    STATE(10), 2,
      sym_variable,
      sym_string,
  [1429] = 8,
    ACTIONS(175), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 1,
      sym_seq_name,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      sym_iden,
    STATE(28), 1,
      sym_expr,
    ACTIONS(181), 2,
      sym_char_literal,
      sym_number,
    STATE(9), 2,
      sym_binary,
      sym_paran,
    STATE(10), 2,
      sym_variable,
      sym_string,
  [1457] = 8,
    ACTIONS(175), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 1,
      sym_seq_name,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      sym_iden,
    STATE(23), 1,
      sym_expr,
    ACTIONS(181), 2,
      sym_char_literal,
      sym_number,
    STATE(9), 2,
      sym_binary,
      sym_paran,
    STATE(10), 2,
      sym_variable,
      sym_string,
  [1485] = 8,
    ACTIONS(175), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 1,
      sym_seq_name,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      sym_iden,
    STATE(29), 1,
      sym_expr,
    ACTIONS(181), 2,
      sym_char_literal,
      sym_number,
    STATE(9), 2,
      sym_binary,
      sym_paran,
    STATE(10), 2,
      sym_variable,
      sym_string,
  [1513] = 8,
    ACTIONS(175), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 1,
      sym_seq_name,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      sym_iden,
    STATE(20), 1,
      sym_expr,
    ACTIONS(181), 2,
      sym_char_literal,
      sym_number,
    STATE(9), 2,
      sym_binary,
      sym_paran,
    STATE(10), 2,
      sym_variable,
      sym_string,
  [1541] = 8,
    ACTIONS(175), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 1,
      sym_seq_name,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      sym_iden,
    STATE(26), 1,
      sym_expr,
    ACTIONS(181), 2,
      sym_char_literal,
      sym_number,
    STATE(9), 2,
      sym_binary,
      sym_paran,
    STATE(10), 2,
      sym_variable,
      sym_string,
  [1569] = 8,
    ACTIONS(175), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 1,
      sym_seq_name,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      sym_iden,
    STATE(31), 1,
      sym_expr,
    ACTIONS(181), 2,
      sym_char_literal,
      sym_number,
    STATE(9), 2,
      sym_binary,
      sym_paran,
    STATE(10), 2,
      sym_variable,
      sym_string,
  [1597] = 8,
    ACTIONS(175), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 1,
      sym_seq_name,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      sym_iden,
    STATE(24), 1,
      sym_expr,
    ACTIONS(181), 2,
      sym_char_literal,
      sym_number,
    STATE(9), 2,
      sym_binary,
      sym_paran,
    STATE(10), 2,
      sym_variable,
      sym_string,
  [1625] = 8,
    ACTIONS(175), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 1,
      sym_seq_name,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      sym_iden,
    STATE(19), 1,
      sym_expr,
    ACTIONS(181), 2,
      sym_char_literal,
      sym_number,
    STATE(9), 2,
      sym_binary,
      sym_paran,
    STATE(10), 2,
      sym_variable,
      sym_string,
  [1653] = 8,
    ACTIONS(175), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 1,
      sym_seq_name,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      sym_iden,
    STATE(25), 1,
      sym_expr,
    ACTIONS(181), 2,
      sym_char_literal,
      sym_number,
    STATE(9), 2,
      sym_binary,
      sym_paran,
    STATE(10), 2,
      sym_variable,
      sym_string,
  [1681] = 8,
    ACTIONS(175), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 1,
      sym_seq_name,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      sym_iden,
    STATE(14), 1,
      sym_expr,
    ACTIONS(181), 2,
      sym_char_literal,
      sym_number,
    STATE(9), 2,
      sym_binary,
      sym_paran,
    STATE(10), 2,
      sym_variable,
      sym_string,
  [1709] = 8,
    ACTIONS(175), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 1,
      sym_seq_name,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      sym_iden,
    STATE(17), 1,
      sym_expr,
    ACTIONS(181), 2,
      sym_char_literal,
      sym_number,
    STATE(9), 2,
      sym_binary,
      sym_paran,
    STATE(10), 2,
      sym_variable,
      sym_string,
  [1737] = 8,
    ACTIONS(175), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 1,
      sym_seq_name,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      sym_iden,
    STATE(15), 1,
      sym_expr,
    ACTIONS(181), 2,
      sym_char_literal,
      sym_number,
    STATE(9), 2,
      sym_binary,
      sym_paran,
    STATE(10), 2,
      sym_variable,
      sym_string,
  [1765] = 8,
    ACTIONS(175), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 1,
      sym_seq_name,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      sym_iden,
    STATE(12), 1,
      sym_expr,
    ACTIONS(181), 2,
      sym_char_literal,
      sym_number,
    STATE(9), 2,
      sym_binary,
      sym_paran,
    STATE(10), 2,
      sym_variable,
      sym_string,
  [1793] = 8,
    ACTIONS(175), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 1,
      sym_seq_name,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      sym_iden,
    STATE(18), 1,
      sym_expr,
    ACTIONS(181), 2,
      sym_char_literal,
      sym_number,
    STATE(9), 2,
      sym_binary,
      sym_paran,
    STATE(10), 2,
      sym_variable,
      sym_string,
  [1821] = 8,
    ACTIONS(175), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 1,
      sym_seq_name,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      sym_iden,
    STATE(27), 1,
      sym_expr,
    ACTIONS(181), 2,
      sym_char_literal,
      sym_number,
    STATE(9), 2,
      sym_binary,
      sym_paran,
    STATE(10), 2,
      sym_variable,
      sym_string,
  [1849] = 8,
    ACTIONS(175), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 1,
      sym_seq_name,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      sym_iden,
    STATE(30), 1,
      sym_expr,
    ACTIONS(181), 2,
      sym_char_literal,
      sym_number,
    STATE(9), 2,
      sym_binary,
      sym_paran,
    STATE(10), 2,
      sym_variable,
      sym_string,
  [1877] = 8,
    ACTIONS(175), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 1,
      sym_seq_name,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      sym_iden,
    STATE(21), 1,
      sym_expr,
    ACTIONS(181), 2,
      sym_char_literal,
      sym_number,
    STATE(9), 2,
      sym_binary,
      sym_paran,
    STATE(10), 2,
      sym_variable,
      sym_string,
  [1905] = 7,
    ACTIONS(185), 1,
      ts_builtin_sym_end,
    ACTIONS(187), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_use,
    ACTIONS(193), 1,
      anon_sym_seq,
    ACTIONS(196), 1,
      anon_sym_rout,
    STATE(65), 2,
      sym_unit,
      aux_sym_source_file_repeat1,
    STATE(70), 3,
      sym_import,
      sym_sequence,
      sym_routine,
  [1930] = 7,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_use,
    ACTIONS(9), 1,
      anon_sym_seq,
    ACTIONS(11), 1,
      anon_sym_rout,
    ACTIONS(199), 1,
      ts_builtin_sym_end,
    STATE(65), 2,
      sym_unit,
      aux_sym_source_file_repeat1,
    STATE(70), 3,
      sym_import,
      sym_sequence,
      sym_routine,
  [1955] = 2,
    ACTIONS(203), 2,
      sym_seq_name,
      sym_iden,
    ACTIONS(201), 4,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      sym_char_literal,
      sym_number,
  [1966] = 4,
    ACTIONS(205), 1,
      sym_string_literal,
    ACTIONS(207), 1,
      anon_sym_LBRACE,
    STATE(115), 1,
      sym_string_content,
    STATE(78), 2,
      sym_string_format,
      aux_sym_string_content_repeat1,
  [1980] = 5,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    STATE(3), 1,
      sym_open_scope,
    STATE(77), 1,
      sym_tree,
    STATE(95), 1,
      sym_param_interface,
  [1996] = 1,
    ACTIONS(211), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
  [2004] = 4,
    ACTIONS(213), 1,
      anon_sym_SQUOTE,
    ACTIONS(215), 1,
      sym_string_literal,
    ACTIONS(218), 1,
      anon_sym_LBRACE,
    STATE(71), 2,
      sym_string_format,
      aux_sym_string_content_repeat1,
  [2018] = 3,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
    ACTIONS(223), 2,
      sym_key_in,
      sym_key_out,
    STATE(83), 2,
      sym_param_def,
      aux_sym_param_interface_repeat1,
  [2030] = 5,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    ACTIONS(225), 1,
      sym_iden,
    STATE(76), 1,
      sym_close_scope,
    STATE(84), 1,
      sym_seq_entry,
    STATE(92), 1,
      aux_sym_sequence_repeat1,
  [2046] = 1,
    ACTIONS(227), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
  [2054] = 1,
    ACTIONS(229), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
  [2062] = 1,
    ACTIONS(231), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
  [2070] = 1,
    ACTIONS(233), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
  [2078] = 4,
    ACTIONS(207), 1,
      anon_sym_LBRACE,
    ACTIONS(235), 1,
      anon_sym_SQUOTE,
    ACTIONS(237), 1,
      sym_string_literal,
    STATE(71), 2,
      sym_string_format,
      aux_sym_string_content_repeat1,
  [2092] = 1,
    ACTIONS(239), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
  [2100] = 5,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    ACTIONS(225), 1,
      sym_iden,
    STATE(73), 1,
      aux_sym_sequence_repeat1,
    STATE(74), 1,
      sym_close_scope,
    STATE(84), 1,
      sym_seq_entry,
  [2116] = 3,
    ACTIONS(241), 1,
      anon_sym_RPAREN,
    ACTIONS(223), 2,
      sym_key_in,
      sym_key_out,
    STATE(72), 2,
      sym_param_def,
      aux_sym_param_interface_repeat1,
  [2128] = 1,
    ACTIONS(243), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_eos,
      sym_bind,
      sym_iden,
  [2136] = 3,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
    ACTIONS(247), 2,
      sym_key_in,
      sym_key_out,
    STATE(83), 2,
      sym_param_def,
      aux_sym_param_interface_repeat1,
  [2148] = 3,
    ACTIONS(250), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_COMMA,
    ACTIONS(254), 2,
      anon_sym_RBRACE,
      sym_iden,
  [2159] = 1,
    ACTIONS(256), 4,
      sym_comment,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_iden,
  [2166] = 4,
    ACTIONS(258), 1,
      anon_sym_RPAREN,
    ACTIONS(260), 1,
      sym_iden,
    STATE(88), 1,
      aux_sym_sub_repeat1,
    STATE(89), 1,
      sym_param_name,
  [2179] = 4,
    ACTIONS(262), 1,
      anon_sym_BQUOTE,
    ACTIONS(264), 1,
      sym_iden,
    STATE(106), 1,
      sym_variable,
    STATE(129), 1,
      sym_string_format_content,
  [2192] = 4,
    ACTIONS(260), 1,
      sym_iden,
    ACTIONS(266), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      sym_param_name,
    STATE(90), 1,
      aux_sym_sub_repeat1,
  [2205] = 3,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(272), 1,
      sym_bind,
    ACTIONS(270), 2,
      anon_sym_RPAREN,
      sym_iden,
  [2216] = 4,
    ACTIONS(274), 1,
      anon_sym_RPAREN,
    ACTIONS(276), 1,
      sym_iden,
    STATE(89), 1,
      sym_param_name,
    STATE(90), 1,
      aux_sym_sub_repeat1,
  [2229] = 4,
    ACTIONS(279), 1,
      sym_eos,
    ACTIONS(281), 1,
      sym_bind,
    ACTIONS(283), 1,
      sym_iden,
    STATE(102), 1,
      sym_label,
  [2242] = 4,
    ACTIONS(285), 1,
      anon_sym_RBRACE,
    ACTIONS(287), 1,
      sym_iden,
    STATE(84), 1,
      sym_seq_entry,
    STATE(92), 1,
      aux_sym_sequence_repeat1,
  [2255] = 2,
    ACTIONS(292), 1,
      sym_string_literal,
    ACTIONS(290), 2,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
  [2263] = 1,
    ACTIONS(294), 3,
      anon_sym_RPAREN,
      sym_key_in,
      sym_key_out,
  [2269] = 3,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    STATE(3), 1,
      sym_open_scope,
    STATE(75), 1,
      sym_tree,
  [2279] = 3,
    ACTIONS(264), 1,
      sym_iden,
    STATE(106), 1,
      sym_variable,
    STATE(121), 1,
      sym_string_format_content,
  [2289] = 3,
    ACTIONS(283), 1,
      sym_iden,
    ACTIONS(296), 1,
      sym_eos,
    STATE(124), 1,
      sym_label,
  [2299] = 2,
    ACTIONS(300), 1,
      sym_string_literal,
    ACTIONS(298), 2,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
  [2307] = 2,
    ACTIONS(302), 1,
      sym_comment,
    ACTIONS(285), 2,
      anon_sym_RBRACE,
      sym_iden,
  [2315] = 2,
    ACTIONS(304), 1,
      sym_iden,
    STATE(122), 1,
      sym_rout_name,
  [2322] = 1,
    ACTIONS(163), 2,
      anon_sym_RBRACE,
      sym_iden,
  [2327] = 2,
    ACTIONS(306), 1,
      sym_eos,
    ACTIONS(308), 1,
      sym_bind,
  [2334] = 2,
    ACTIONS(310), 1,
      anon_sym_LBRACE,
    STATE(80), 1,
      sym_open_scope,
  [2341] = 2,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
    STATE(119), 1,
      sym_string,
  [2348] = 1,
    ACTIONS(312), 2,
      anon_sym_RBRACE,
      sym_iden,
  [2353] = 2,
    ACTIONS(314), 1,
      anon_sym_DOT,
    ACTIONS(316), 1,
      anon_sym_RBRACE,
  [2360] = 2,
    ACTIONS(264), 1,
      sym_iden,
    STATE(120), 1,
      sym_variable,
  [2367] = 1,
    ACTIONS(318), 2,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
  [2372] = 1,
    ACTIONS(274), 2,
      anon_sym_RPAREN,
      sym_iden,
  [2377] = 1,
    ACTIONS(285), 2,
      anon_sym_RBRACE,
      sym_iden,
  [2382] = 1,
    ACTIONS(320), 2,
      sym_eos,
      sym_bind,
  [2387] = 1,
    ACTIONS(322), 2,
      anon_sym_RPAREN,
      sym_iden,
  [2392] = 2,
    ACTIONS(260), 1,
      sym_iden,
    STATE(125), 1,
      sym_param_name,
  [2399] = 2,
    ACTIONS(304), 1,
      sym_iden,
    STATE(69), 1,
      sym_rout_name,
  [2406] = 1,
    ACTIONS(324), 1,
      anon_sym_SQUOTE,
  [2410] = 1,
    ACTIONS(326), 1,
      ts_builtin_sym_end,
  [2414] = 1,
    ACTIONS(328), 1,
      sym_eos,
  [2418] = 1,
    ACTIONS(330), 1,
      sym_eos,
  [2422] = 1,
    ACTIONS(332), 1,
      sym_eos,
  [2426] = 1,
    ACTIONS(334), 1,
      anon_sym_RBRACE,
  [2430] = 1,
    ACTIONS(336), 1,
      anon_sym_RBRACE,
  [2434] = 1,
    ACTIONS(338), 1,
      anon_sym_LPAREN,
  [2438] = 1,
    ACTIONS(340), 1,
      sym_eos,
  [2442] = 1,
    ACTIONS(342), 1,
      sym_eos,
  [2446] = 1,
    ACTIONS(344), 1,
      sym_eos,
  [2450] = 1,
    ACTIONS(346), 1,
      anon_sym_LBRACE,
  [2454] = 1,
    ACTIONS(348), 1,
      anon_sym_LBRACE,
  [2458] = 1,
    ACTIONS(350), 1,
      sym_seq_name,
  [2462] = 1,
    ACTIONS(352), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 70,
  [SMALL_STATE(4)] = 140,
  [SMALL_STATE(5)] = 207,
  [SMALL_STATE(6)] = 242,
  [SMALL_STATE(7)] = 305,
  [SMALL_STATE(8)] = 338,
  [SMALL_STATE(9)] = 370,
  [SMALL_STATE(10)] = 402,
  [SMALL_STATE(11)] = 434,
  [SMALL_STATE(12)] = 466,
  [SMALL_STATE(13)] = 501,
  [SMALL_STATE(14)] = 536,
  [SMALL_STATE(15)] = 569,
  [SMALL_STATE(16)] = 604,
  [SMALL_STATE(17)] = 633,
  [SMALL_STATE(18)] = 662,
  [SMALL_STATE(19)] = 691,
  [SMALL_STATE(20)] = 720,
  [SMALL_STATE(21)] = 749,
  [SMALL_STATE(22)] = 778,
  [SMALL_STATE(23)] = 807,
  [SMALL_STATE(24)] = 836,
  [SMALL_STATE(25)] = 865,
  [SMALL_STATE(26)] = 894,
  [SMALL_STATE(27)] = 923,
  [SMALL_STATE(28)] = 952,
  [SMALL_STATE(29)] = 981,
  [SMALL_STATE(30)] = 1010,
  [SMALL_STATE(31)] = 1039,
  [SMALL_STATE(32)] = 1068,
  [SMALL_STATE(33)] = 1097,
  [SMALL_STATE(34)] = 1119,
  [SMALL_STATE(35)] = 1141,
  [SMALL_STATE(36)] = 1163,
  [SMALL_STATE(37)] = 1181,
  [SMALL_STATE(38)] = 1199,
  [SMALL_STATE(39)] = 1217,
  [SMALL_STATE(40)] = 1235,
  [SMALL_STATE(41)] = 1253,
  [SMALL_STATE(42)] = 1271,
  [SMALL_STATE(43)] = 1289,
  [SMALL_STATE(44)] = 1317,
  [SMALL_STATE(45)] = 1345,
  [SMALL_STATE(46)] = 1373,
  [SMALL_STATE(47)] = 1401,
  [SMALL_STATE(48)] = 1429,
  [SMALL_STATE(49)] = 1457,
  [SMALL_STATE(50)] = 1485,
  [SMALL_STATE(51)] = 1513,
  [SMALL_STATE(52)] = 1541,
  [SMALL_STATE(53)] = 1569,
  [SMALL_STATE(54)] = 1597,
  [SMALL_STATE(55)] = 1625,
  [SMALL_STATE(56)] = 1653,
  [SMALL_STATE(57)] = 1681,
  [SMALL_STATE(58)] = 1709,
  [SMALL_STATE(59)] = 1737,
  [SMALL_STATE(60)] = 1765,
  [SMALL_STATE(61)] = 1793,
  [SMALL_STATE(62)] = 1821,
  [SMALL_STATE(63)] = 1849,
  [SMALL_STATE(64)] = 1877,
  [SMALL_STATE(65)] = 1905,
  [SMALL_STATE(66)] = 1930,
  [SMALL_STATE(67)] = 1955,
  [SMALL_STATE(68)] = 1966,
  [SMALL_STATE(69)] = 1980,
  [SMALL_STATE(70)] = 1996,
  [SMALL_STATE(71)] = 2004,
  [SMALL_STATE(72)] = 2018,
  [SMALL_STATE(73)] = 2030,
  [SMALL_STATE(74)] = 2046,
  [SMALL_STATE(75)] = 2054,
  [SMALL_STATE(76)] = 2062,
  [SMALL_STATE(77)] = 2070,
  [SMALL_STATE(78)] = 2078,
  [SMALL_STATE(79)] = 2092,
  [SMALL_STATE(80)] = 2100,
  [SMALL_STATE(81)] = 2116,
  [SMALL_STATE(82)] = 2128,
  [SMALL_STATE(83)] = 2136,
  [SMALL_STATE(84)] = 2148,
  [SMALL_STATE(85)] = 2159,
  [SMALL_STATE(86)] = 2166,
  [SMALL_STATE(87)] = 2179,
  [SMALL_STATE(88)] = 2192,
  [SMALL_STATE(89)] = 2205,
  [SMALL_STATE(90)] = 2216,
  [SMALL_STATE(91)] = 2229,
  [SMALL_STATE(92)] = 2242,
  [SMALL_STATE(93)] = 2255,
  [SMALL_STATE(94)] = 2263,
  [SMALL_STATE(95)] = 2269,
  [SMALL_STATE(96)] = 2279,
  [SMALL_STATE(97)] = 2289,
  [SMALL_STATE(98)] = 2299,
  [SMALL_STATE(99)] = 2307,
  [SMALL_STATE(100)] = 2315,
  [SMALL_STATE(101)] = 2322,
  [SMALL_STATE(102)] = 2327,
  [SMALL_STATE(103)] = 2334,
  [SMALL_STATE(104)] = 2341,
  [SMALL_STATE(105)] = 2348,
  [SMALL_STATE(106)] = 2353,
  [SMALL_STATE(107)] = 2360,
  [SMALL_STATE(108)] = 2367,
  [SMALL_STATE(109)] = 2372,
  [SMALL_STATE(110)] = 2377,
  [SMALL_STATE(111)] = 2382,
  [SMALL_STATE(112)] = 2387,
  [SMALL_STATE(113)] = 2392,
  [SMALL_STATE(114)] = 2399,
  [SMALL_STATE(115)] = 2406,
  [SMALL_STATE(116)] = 2410,
  [SMALL_STATE(117)] = 2414,
  [SMALL_STATE(118)] = 2418,
  [SMALL_STATE(119)] = 2422,
  [SMALL_STATE(120)] = 2426,
  [SMALL_STATE(121)] = 2430,
  [SMALL_STATE(122)] = 2434,
  [SMALL_STATE(123)] = 2438,
  [SMALL_STATE(124)] = 2442,
  [SMALL_STATE(125)] = 2446,
  [SMALL_STATE(126)] = 2450,
  [SMALL_STATE(127)] = 2454,
  [SMALL_STATE(128)] = 2458,
  [SMALL_STATE(129)] = 2462,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(36),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(64),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(47),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(49),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(51),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(100),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(97),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(91),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(54),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(55),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(61),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(56),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(58),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(6),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary, 3, .production_id = 2),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary, 3, .production_id = 2),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 1),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, .production_id = 1),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1, .production_id = 1),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paran, 3),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paran, 3),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sub_repeat1, 3),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_void, 2),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_debug, 2),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_write, 2),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 3),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trans, 4),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pers, 4),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_put, 4),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 4),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tree, 2),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_close_scope, 1),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tree, 3),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_open_scope, 1),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defer, 2),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_iter, 5),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 7),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_count, 7),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(70),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(104),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(128),
  [196] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(114),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_op, 1),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_op, 1),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit, 1),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_content_repeat1, 2),
  [215] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_content_repeat1, 2), SHIFT_REPEAT(71),
  [218] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_content_repeat1, 2), SHIFT_REPEAT(87),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence, 4),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_routine, 4),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence, 5),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_routine, 3),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_content, 1),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 3),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_name, 1),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_param_interface_repeat1, 2),
  [247] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_param_interface_repeat1, 2), SHIFT_REPEAT(113),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 1),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_seq_entry, 1),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sub_repeat1, 1),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sub_repeat1, 2),
  [276] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sub_repeat1, 2), SHIFT_REPEAT(82),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 1),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2),
  [287] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2), SHIFT_REPEAT(85),
  [290] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_format, 4),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_format, 4),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_def, 3),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lab, 1),
  [298] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_format, 3),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_format, 3),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 2),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 3),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_format_content, 1),
  [318] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rout_name, 1),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 1),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sub_repeat1, 4),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [326] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub, 4),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [334] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_format_content, 3),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [340] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub, 5),
  [342] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lab, 2),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [346] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_interface, 3),
  [348] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_interface, 2),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_snug(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
