#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 127
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 96
#define ALIAS_COUNT 0
#define TOKEN_COUNT 54
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 3

enum {
  sym_comment = 1,
  anon_sym_use = 2,
  anon_sym_seq = 3,
  anon_sym_COMMA = 4,
  anon_sym_rout = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  sym_seq_name = 8,
  anon_sym_put = 9,
  anon_sym_EQ = 10,
  anon_sym_debug = 11,
  anon_sym_trans = 12,
  anon_sym_pers = 13,
  anon_sym_sub = 14,
  anon_sym_lab = 15,
  anon_sym_jump = 16,
  anon_sym_write = 17,
  anon_sym_void = 18,
  anon_sym_iter = 19,
  anon_sym_enum = 20,
  anon_sym_AT = 21,
  anon_sym_count = 22,
  anon_sym_DOT_DOT = 23,
  anon_sym_PLUS = 24,
  anon_sym_DASH = 25,
  anon_sym_STAR = 26,
  anon_sym_GT = 27,
  anon_sym_LT = 28,
  anon_sym_DOT = 29,
  anon_sym_PIPE_PIPE = 30,
  anon_sym_AMP_AMP = 31,
  anon_sym_PIPE = 32,
  anon_sym_AMP = 33,
  anon_sym_GT_EQ = 34,
  anon_sym_LT_EQ = 35,
  anon_sym_EQ_EQ = 36,
  anon_sym_BANG_EQ = 37,
  anon_sym_PLUS_EQ = 38,
  anon_sym_DASH_EQ = 39,
  anon_sym_EQ_PLUS = 40,
  anon_sym_EQ_DASH = 41,
  anon_sym_SQUOTE = 42,
  sym_string_literal = 43,
  anon_sym_LBRACE = 44,
  anon_sym_BQUOTE = 45,
  anon_sym_RBRACE = 46,
  sym_char_literal = 47,
  sym_key_in = 48,
  sym_key_out = 49,
  sym_eos = 50,
  sym_bind = 51,
  sym_iden = 52,
  sym_number = 53,
  sym_source_file = 54,
  sym_unit = 55,
  sym_import = 56,
  sym_sequence = 57,
  sym_routine = 58,
  sym_tree = 59,
  sym_param_interface = 60,
  sym_param_def = 61,
  sym_param_name = 62,
  sym_rout_name = 63,
  sym_seq_entry = 64,
  sym_statement = 65,
  sym_put = 66,
  sym_debug = 67,
  sym_trans = 68,
  sym_pers = 69,
  sym_sub = 70,
  sym_lab = 71,
  sym_jump = 72,
  sym_write = 73,
  sym_void = 74,
  sym_iter = 75,
  sym_enum = 76,
  sym_count = 77,
  sym_expr = 78,
  sym_binary = 79,
  sym_paran = 80,
  sym_op = 81,
  sym_label = 82,
  sym_variable = 83,
  sym_string = 84,
  sym_string_content = 85,
  sym_string_format = 86,
  sym_string_format_content = 87,
  sym_open_scope = 88,
  sym_close_scope = 89,
  aux_sym_source_file_repeat1 = 90,
  aux_sym_sequence_repeat1 = 91,
  aux_sym_tree_repeat1 = 92,
  aux_sym_param_interface_repeat1 = 93,
  aux_sym_sub_repeat1 = 94,
  aux_sym_string_content_repeat1 = 95,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_use] = "use",
  [anon_sym_seq] = "seq",
  [anon_sym_COMMA] = ",",
  [anon_sym_rout] = "rout",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_seq_name] = "seq_name",
  [anon_sym_put] = "put",
  [anon_sym_EQ] = "=",
  [anon_sym_debug] = "debug",
  [anon_sym_trans] = "trans",
  [anon_sym_pers] = "pers",
  [anon_sym_sub] = "sub",
  [anon_sym_lab] = "lab",
  [anon_sym_jump] = "jump",
  [anon_sym_write] = "write",
  [anon_sym_void] = "void",
  [anon_sym_iter] = "iter",
  [anon_sym_enum] = "enum",
  [anon_sym_AT] = "@",
  [anon_sym_count] = "count",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_DOT] = ".",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE] = "|",
  [anon_sym_AMP] = "&",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_PLUS_EQ] = "+=",
  [anon_sym_DASH_EQ] = "-=",
  [anon_sym_EQ_PLUS] = "=+",
  [anon_sym_EQ_DASH] = "=-",
  [anon_sym_SQUOTE] = "'",
  [sym_string_literal] = "string_literal",
  [anon_sym_LBRACE] = "{",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_RBRACE] = "}",
  [sym_char_literal] = "char_literal",
  [sym_key_in] = "key_in",
  [sym_key_out] = "key_out",
  [sym_eos] = "eos",
  [sym_bind] = "bind",
  [sym_iden] = "iden",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym_unit] = "unit",
  [sym_import] = "import",
  [sym_sequence] = "sequence",
  [sym_routine] = "routine",
  [sym_tree] = "tree",
  [sym_param_interface] = "param_interface",
  [sym_param_def] = "param_def",
  [sym_param_name] = "param_name",
  [sym_rout_name] = "rout_name",
  [sym_seq_entry] = "seq_entry",
  [sym_statement] = "statement",
  [sym_put] = "put",
  [sym_debug] = "debug",
  [sym_trans] = "trans",
  [sym_pers] = "pers",
  [sym_sub] = "sub",
  [sym_lab] = "lab",
  [sym_jump] = "jump",
  [sym_write] = "write",
  [sym_void] = "void",
  [sym_iter] = "iter",
  [sym_enum] = "enum",
  [sym_count] = "count",
  [sym_expr] = "expr",
  [sym_binary] = "binary",
  [sym_paran] = "paran",
  [sym_op] = "op",
  [sym_label] = "label",
  [sym_variable] = "variable",
  [sym_string] = "string",
  [sym_string_content] = "string_content",
  [sym_string_format] = "string_format",
  [sym_string_format_content] = "string_format_content",
  [sym_open_scope] = "open_scope",
  [sym_close_scope] = "close_scope",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_sequence_repeat1] = "sequence_repeat1",
  [aux_sym_tree_repeat1] = "tree_repeat1",
  [aux_sym_param_interface_repeat1] = "param_interface_repeat1",
  [aux_sym_sub_repeat1] = "sub_repeat1",
  [aux_sym_string_content_repeat1] = "string_content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_seq] = anon_sym_seq,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_rout] = anon_sym_rout,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_seq_name] = sym_seq_name,
  [anon_sym_put] = anon_sym_put,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_debug] = anon_sym_debug,
  [anon_sym_trans] = anon_sym_trans,
  [anon_sym_pers] = anon_sym_pers,
  [anon_sym_sub] = anon_sym_sub,
  [anon_sym_lab] = anon_sym_lab,
  [anon_sym_jump] = anon_sym_jump,
  [anon_sym_write] = anon_sym_write,
  [anon_sym_void] = anon_sym_void,
  [anon_sym_iter] = anon_sym_iter,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_count] = anon_sym_count,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_PLUS_EQ] = anon_sym_PLUS_EQ,
  [anon_sym_DASH_EQ] = anon_sym_DASH_EQ,
  [anon_sym_EQ_PLUS] = anon_sym_EQ_PLUS,
  [anon_sym_EQ_DASH] = anon_sym_EQ_DASH,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_string_literal] = sym_string_literal,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_char_literal] = sym_char_literal,
  [sym_key_in] = sym_key_in,
  [sym_key_out] = sym_key_out,
  [sym_eos] = sym_eos,
  [sym_bind] = sym_bind,
  [sym_iden] = sym_iden,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym_unit] = sym_unit,
  [sym_import] = sym_import,
  [sym_sequence] = sym_sequence,
  [sym_routine] = sym_routine,
  [sym_tree] = sym_tree,
  [sym_param_interface] = sym_param_interface,
  [sym_param_def] = sym_param_def,
  [sym_param_name] = sym_param_name,
  [sym_rout_name] = sym_rout_name,
  [sym_seq_entry] = sym_seq_entry,
  [sym_statement] = sym_statement,
  [sym_put] = sym_put,
  [sym_debug] = sym_debug,
  [sym_trans] = sym_trans,
  [sym_pers] = sym_pers,
  [sym_sub] = sym_sub,
  [sym_lab] = sym_lab,
  [sym_jump] = sym_jump,
  [sym_write] = sym_write,
  [sym_void] = sym_void,
  [sym_iter] = sym_iter,
  [sym_enum] = sym_enum,
  [sym_count] = sym_count,
  [sym_expr] = sym_expr,
  [sym_binary] = sym_binary,
  [sym_paran] = sym_paran,
  [sym_op] = sym_op,
  [sym_label] = sym_label,
  [sym_variable] = sym_variable,
  [sym_string] = sym_string,
  [sym_string_content] = sym_string_content,
  [sym_string_format] = sym_string_format,
  [sym_string_format_content] = sym_string_format_content,
  [sym_open_scope] = sym_open_scope,
  [sym_close_scope] = sym_close_scope,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_sequence_repeat1] = aux_sym_sequence_repeat1,
  [aux_sym_tree_repeat1] = aux_sym_tree_repeat1,
  [aux_sym_param_interface_repeat1] = aux_sym_param_interface_repeat1,
  [aux_sym_sub_repeat1] = aux_sym_sub_repeat1,
  [aux_sym_string_content_repeat1] = aux_sym_string_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_seq] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rout] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_seq_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_put] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_debug] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_trans] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pers] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sub] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_lab] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_jump] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_write] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_void] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_iter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_count] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_char_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_key_in] = {
    .visible = true,
    .named = true,
  },
  [sym_key_out] = {
    .visible = true,
    .named = true,
  },
  [sym_eos] = {
    .visible = true,
    .named = true,
  },
  [sym_bind] = {
    .visible = true,
    .named = true,
  },
  [sym_iden] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_unit] = {
    .visible = true,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_routine] = {
    .visible = true,
    .named = true,
  },
  [sym_tree] = {
    .visible = true,
    .named = true,
  },
  [sym_param_interface] = {
    .visible = true,
    .named = true,
  },
  [sym_param_def] = {
    .visible = true,
    .named = true,
  },
  [sym_param_name] = {
    .visible = true,
    .named = true,
  },
  [sym_rout_name] = {
    .visible = true,
    .named = true,
  },
  [sym_seq_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_put] = {
    .visible = true,
    .named = true,
  },
  [sym_debug] = {
    .visible = true,
    .named = true,
  },
  [sym_trans] = {
    .visible = true,
    .named = true,
  },
  [sym_pers] = {
    .visible = true,
    .named = true,
  },
  [sym_sub] = {
    .visible = true,
    .named = true,
  },
  [sym_lab] = {
    .visible = true,
    .named = true,
  },
  [sym_jump] = {
    .visible = true,
    .named = true,
  },
  [sym_write] = {
    .visible = true,
    .named = true,
  },
  [sym_void] = {
    .visible = true,
    .named = true,
  },
  [sym_iter] = {
    .visible = true,
    .named = true,
  },
  [sym_enum] = {
    .visible = true,
    .named = true,
  },
  [sym_count] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binary] = {
    .visible = true,
    .named = true,
  },
  [sym_paran] = {
    .visible = true,
    .named = true,
  },
  [sym_op] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_string_format] = {
    .visible = true,
    .named = true,
  },
  [sym_string_format_content] = {
    .visible = true,
    .named = true,
  },
  [sym_open_scope] = {
    .visible = true,
    .named = true,
  },
  [sym_close_scope] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tree_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_param_interface_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sub_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_content = 1,
  field_left = 2,
  field_op = 3,
  field_right = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_left] = "left",
  [field_op] = "op",
  [field_right] = "right",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_content, 0},
  [1] =
    {field_left, 0},
    {field_op, 1},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 40,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(52);
      if (lookahead == '!') ADVANCE(5);
      if (lookahead == '"') ADVANCE(50);
      if (lookahead == '&') ADVANCE(86);
      if (lookahead == '\'') ADVANCE(95);
      if (lookahead == '(') ADVANCE(58);
      if (lookahead == ')') ADVANCE(59);
      if (lookahead == '*') ADVANCE(79);
      if (lookahead == '+') ADVANCE(77);
      if (lookahead == ',') ADVANCE(56);
      if (lookahead == '-') ADVANCE(78);
      if (lookahead == '.') ADVANCE(82);
      if (lookahead == ';') ADVANCE(104);
      if (lookahead == '<') ADVANCE(81);
      if (lookahead == '=') ADVANCE(63);
      if (lookahead == '>') ADVANCE(80);
      if (lookahead == '@') ADVANCE(74);
      if (lookahead == '`') ADVANCE(99);
      if (lookahead == 'c') ADVANCE(28);
      if (lookahead == 'd') ADVANCE(12);
      if (lookahead == 'e') ADVANCE(26);
      if (lookahead == 'i') ADVANCE(23);
      if (lookahead == 'j') ADVANCE(44);
      if (lookahead == 'l') ADVANCE(6);
      if (lookahead == 'o') ADVANCE(45);
      if (lookahead == 'p') ADVANCE(16);
      if (lookahead == 'r') ADVANCE(29);
      if (lookahead == 's') ADVANCE(13);
      if (lookahead == 't') ADVANCE(33);
      if (lookahead == 'u') ADVANCE(38);
      if (lookahead == 'v') ADVANCE(27);
      if (lookahead == 'w') ADVANCE(35);
      if (lookahead == '{') ADVANCE(98);
      if (lookahead == '|') ADVANCE(85);
      if (lookahead == '}') ADVANCE(100);
      if (lookahead == '~') ADVANCE(105);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(107);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(61);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(5);
      if (lookahead == '"') ADVANCE(50);
      if (lookahead == '&') ADVANCE(86);
      if (lookahead == ')') ADVANCE(59);
      if (lookahead == '*') ADVANCE(79);
      if (lookahead == '+') ADVANCE(77);
      if (lookahead == ',') ADVANCE(56);
      if (lookahead == '-') ADVANCE(78);
      if (lookahead == '.') ADVANCE(82);
      if (lookahead == ';') ADVANCE(104);
      if (lookahead == '<') ADVANCE(81);
      if (lookahead == '=') ADVANCE(63);
      if (lookahead == '>') ADVANCE(80);
      if (lookahead == '@') ADVANCE(74);
      if (lookahead == '`') ADVANCE(99);
      if (lookahead == '{') ADVANCE(98);
      if (lookahead == '|') ADVANCE(85);
      if (lookahead == '}') ADVANCE(100);
      if (lookahead == '~') ADVANCE(105);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(95);
      if (lookahead == '(') ADVANCE(58);
      if (lookahead == '`') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(107);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(60);
      if (lookahead == ':' ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(95);
      if (lookahead == '{') ADVANCE(98);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(90);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == 'b') ADVANCE(68);
      END_STATE();
    case 9:
      if (lookahead == 'b') ADVANCE(67);
      END_STATE();
    case 10:
      if (lookahead == 'b') ADVANCE(46);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(71);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(31);
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(34);
      if (lookahead == 'u') ADVANCE(40);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 18:
      if (lookahead == 'g') ADVANCE(64);
      END_STATE();
    case 19:
      if (lookahead == 'i') ADVANCE(11);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(43);
      END_STATE();
    case 21:
      if (lookahead == 'm') ADVANCE(30);
      END_STATE();
    case 22:
      if (lookahead == 'm') ADVANCE(73);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(102);
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(37);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(42);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(47);
      END_STATE();
    case 29:
      if (lookahead == 'o') ADVANCE(49);
      END_STATE();
    case 30:
      if (lookahead == 'p') ADVANCE(69);
      END_STATE();
    case 31:
      if (lookahead == 'q') ADVANCE(55);
      END_STATE();
    case 32:
      if (lookahead == 'r') ADVANCE(72);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 36:
      if (lookahead == 's') ADVANCE(66);
      END_STATE();
    case 37:
      if (lookahead == 's') ADVANCE(65);
      END_STATE();
    case 38:
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(103);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(62);
      END_STATE();
    case 41:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(75);
      END_STATE();
    case 43:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 44:
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 45:
      if (lookahead == 'u') ADVANCE(39);
      END_STATE();
    case 46:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 47:
      if (lookahead == 'u') ADVANCE(25);
      END_STATE();
    case 48:
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 49:
      if (lookahead == 'u') ADVANCE(41);
      END_STATE();
    case 50:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 51:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(101);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_seq);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_rout);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_seq_name);
      if (lookahead == '_') ADVANCE(106);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_seq_name);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_put);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '+') ADVANCE(93);
      if (lookahead == '-') ADVANCE(94);
      if (lookahead == '=') ADVANCE(89);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_debug);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_trans);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_pers);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_sub);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_lab);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_jump);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_write);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_void);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_iter);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_count);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '=') ADVANCE(91);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '=') ADVANCE(92);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(87);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(88);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(76);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '|') ADVANCE(83);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == '&') ADVANCE(84);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_PLUS_EQ);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_DASH_EQ);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_EQ_PLUS);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_EQ_DASH);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_string_literal);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_string_literal);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_char_literal);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_key_in);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_key_out);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_eos);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_bind);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_iden);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(107);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 4},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 4},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 4},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 2},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 2},
  [84] = {.lex_state = 2},
  [85] = {.lex_state = 2},
  [86] = {.lex_state = 2},
  [87] = {.lex_state = 2},
  [88] = {.lex_state = 2},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 4},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 2},
  [93] = {.lex_state = 4},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 2},
  [97] = {.lex_state = 2},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 2},
  [103] = {.lex_state = 2},
  [104] = {.lex_state = 2},
  [105] = {.lex_state = 2},
  [106] = {.lex_state = 2},
  [107] = {.lex_state = 2},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_seq] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_rout] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_seq_name] = ACTIONS(1),
    [anon_sym_put] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_debug] = ACTIONS(1),
    [anon_sym_trans] = ACTIONS(1),
    [anon_sym_pers] = ACTIONS(1),
    [anon_sym_sub] = ACTIONS(1),
    [anon_sym_lab] = ACTIONS(1),
    [anon_sym_jump] = ACTIONS(1),
    [anon_sym_write] = ACTIONS(1),
    [anon_sym_void] = ACTIONS(1),
    [anon_sym_iter] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_count] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_PLUS_EQ] = ACTIONS(1),
    [anon_sym_DASH_EQ] = ACTIONS(1),
    [anon_sym_EQ_PLUS] = ACTIONS(1),
    [anon_sym_EQ_DASH] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_key_in] = ACTIONS(1),
    [sym_key_out] = ACTIONS(1),
    [sym_eos] = ACTIONS(1),
    [sym_bind] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(111),
    [sym_unit] = STATE(63),
    [sym_import] = STATE(74),
    [sym_sequence] = STATE(74),
    [sym_routine] = STATE(74),
    [aux_sym_source_file_repeat1] = STATE(63),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [anon_sym_use] = ACTIONS(7),
    [anon_sym_seq] = ACTIONS(9),
    [anon_sym_rout] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 18,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_put,
    ACTIONS(17), 1,
      anon_sym_debug,
    ACTIONS(19), 1,
      anon_sym_trans,
    ACTIONS(21), 1,
      anon_sym_pers,
    ACTIONS(23), 1,
      anon_sym_sub,
    ACTIONS(25), 1,
      anon_sym_lab,
    ACTIONS(27), 1,
      anon_sym_jump,
    ACTIONS(29), 1,
      anon_sym_write,
    ACTIONS(31), 1,
      anon_sym_void,
    ACTIONS(33), 1,
      anon_sym_iter,
    ACTIONS(35), 1,
      anon_sym_enum,
    ACTIONS(37), 1,
      anon_sym_count,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    STATE(34), 1,
      sym_close_scope,
    STATE(4), 2,
      sym_statement,
      aux_sym_tree_repeat1,
    STATE(35), 3,
      sym_iter,
      sym_enum,
      sym_count,
    STATE(118), 9,
      sym_put,
      sym_debug,
      sym_trans,
      sym_pers,
      sym_sub,
      sym_lab,
      sym_jump,
      sym_write,
      sym_void,
  [66] = 18,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_put,
    ACTIONS(17), 1,
      anon_sym_debug,
    ACTIONS(19), 1,
      anon_sym_trans,
    ACTIONS(21), 1,
      anon_sym_pers,
    ACTIONS(23), 1,
      anon_sym_sub,
    ACTIONS(25), 1,
      anon_sym_lab,
    ACTIONS(27), 1,
      anon_sym_jump,
    ACTIONS(29), 1,
      anon_sym_write,
    ACTIONS(31), 1,
      anon_sym_void,
    ACTIONS(33), 1,
      anon_sym_iter,
    ACTIONS(35), 1,
      anon_sym_enum,
    ACTIONS(37), 1,
      anon_sym_count,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      sym_close_scope,
    STATE(2), 2,
      sym_statement,
      aux_sym_tree_repeat1,
    STATE(35), 3,
      sym_iter,
      sym_enum,
      sym_count,
    STATE(118), 9,
      sym_put,
      sym_debug,
      sym_trans,
      sym_pers,
      sym_sub,
      sym_lab,
      sym_jump,
      sym_write,
      sym_void,
  [132] = 17,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(44), 1,
      anon_sym_put,
    ACTIONS(47), 1,
      anon_sym_debug,
    ACTIONS(50), 1,
      anon_sym_trans,
    ACTIONS(53), 1,
      anon_sym_pers,
    ACTIONS(56), 1,
      anon_sym_sub,
    ACTIONS(59), 1,
      anon_sym_lab,
    ACTIONS(62), 1,
      anon_sym_jump,
    ACTIONS(65), 1,
      anon_sym_write,
    ACTIONS(68), 1,
      anon_sym_void,
    ACTIONS(71), 1,
      anon_sym_iter,
    ACTIONS(74), 1,
      anon_sym_enum,
    ACTIONS(77), 1,
      anon_sym_count,
    ACTIONS(80), 1,
      anon_sym_RBRACE,
    STATE(4), 2,
      sym_statement,
      aux_sym_tree_repeat1,
    STATE(35), 3,
      sym_iter,
      sym_enum,
      sym_count,
    STATE(118), 9,
      sym_put,
      sym_debug,
      sym_trans,
      sym_pers,
      sym_sub,
      sym_lab,
      sym_jump,
      sym_write,
      sym_void,
  [195] = 2,
    ACTIONS(84), 8,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(82), 20,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AT,
      anon_sym_DOT_DOT,
      anon_sym_STAR,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_eos,
      sym_bind,
      sym_iden,
  [228] = 3,
    STATE(43), 1,
      sym_op,
    ACTIONS(88), 8,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(86), 19,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AT,
      anon_sym_DOT_DOT,
      anon_sym_STAR,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
      anon_sym_LBRACE,
      sym_eos,
      sym_bind,
      sym_iden,
  [263] = 2,
    ACTIONS(92), 8,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(90), 19,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AT,
      anon_sym_DOT_DOT,
      anon_sym_STAR,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
      anon_sym_LBRACE,
      sym_eos,
      sym_bind,
      sym_iden,
  [295] = 2,
    ACTIONS(96), 8,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(94), 19,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AT,
      anon_sym_DOT_DOT,
      anon_sym_STAR,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
      anon_sym_LBRACE,
      sym_eos,
      sym_bind,
      sym_iden,
  [327] = 2,
    ACTIONS(100), 8,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(98), 19,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AT,
      anon_sym_DOT_DOT,
      anon_sym_STAR,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
      anon_sym_LBRACE,
      sym_eos,
      sym_bind,
      sym_iden,
  [359] = 2,
    ACTIONS(104), 8,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(102), 19,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AT,
      anon_sym_DOT_DOT,
      anon_sym_STAR,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
      anon_sym_LBRACE,
      sym_eos,
      sym_bind,
      sym_iden,
  [391] = 6,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    STATE(3), 1,
      sym_open_scope,
    STATE(37), 1,
      sym_tree,
    STATE(43), 1,
      sym_op,
    ACTIONS(106), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(108), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [426] = 5,
    ACTIONS(112), 1,
      anon_sym_COMMA,
    STATE(43), 1,
      sym_op,
    ACTIONS(114), 2,
      anon_sym_RPAREN,
      sym_iden,
    ACTIONS(106), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(108), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [459] = 6,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    STATE(3), 1,
      sym_open_scope,
    STATE(38), 1,
      sym_tree,
    STATE(43), 1,
      sym_op,
    ACTIONS(106), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(108), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [494] = 6,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    STATE(3), 1,
      sym_open_scope,
    STATE(39), 1,
      sym_tree,
    STATE(43), 1,
      sym_op,
    ACTIONS(106), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(108), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [529] = 4,
    ACTIONS(116), 1,
      sym_eos,
    STATE(43), 1,
      sym_op,
    ACTIONS(106), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(108), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [558] = 4,
    ACTIONS(118), 1,
      anon_sym_DOT_DOT,
    STATE(43), 1,
      sym_op,
    ACTIONS(106), 7,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DOT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(108), 11,
      anon_sym_STAR,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [587] = 4,
    ACTIONS(120), 1,
      anon_sym_EQ,
    STATE(43), 1,
      sym_op,
    ACTIONS(106), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(108), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [616] = 4,
    ACTIONS(122), 1,
      sym_eos,
    STATE(43), 1,
      sym_op,
    ACTIONS(106), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(108), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [645] = 4,
    ACTIONS(124), 1,
      sym_bind,
    STATE(43), 1,
      sym_op,
    ACTIONS(106), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(108), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [674] = 4,
    ACTIONS(126), 1,
      sym_bind,
    STATE(43), 1,
      sym_op,
    ACTIONS(106), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(108), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [703] = 4,
    ACTIONS(128), 1,
      sym_eos,
    STATE(43), 1,
      sym_op,
    ACTIONS(106), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(108), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [732] = 4,
    ACTIONS(130), 1,
      sym_eos,
    STATE(43), 1,
      sym_op,
    ACTIONS(106), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(108), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [761] = 4,
    ACTIONS(132), 1,
      sym_bind,
    STATE(43), 1,
      sym_op,
    ACTIONS(106), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(108), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [790] = 4,
    ACTIONS(134), 1,
      anon_sym_AT,
    STATE(43), 1,
      sym_op,
    ACTIONS(106), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(108), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [819] = 4,
    ACTIONS(136), 1,
      sym_bind,
    STATE(43), 1,
      sym_op,
    ACTIONS(106), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(108), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [848] = 4,
    ACTIONS(138), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      sym_op,
    ACTIONS(106), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(108), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [877] = 4,
    ACTIONS(140), 1,
      sym_eos,
    STATE(43), 1,
      sym_op,
    ACTIONS(106), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(108), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [906] = 4,
    ACTIONS(142), 1,
      sym_eos,
    STATE(43), 1,
      sym_op,
    ACTIONS(106), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(108), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [935] = 4,
    ACTIONS(144), 1,
      sym_eos,
    STATE(43), 1,
      sym_op,
    ACTIONS(106), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(108), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [964] = 4,
    ACTIONS(146), 1,
      sym_eos,
    STATE(43), 1,
      sym_op,
    ACTIONS(106), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(108), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [993] = 4,
    ACTIONS(148), 1,
      sym_bind,
    STATE(43), 1,
      sym_op,
    ACTIONS(106), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(108), 12,
      anon_sym_STAR,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_EQ_PLUS,
      anon_sym_EQ_DASH,
  [1022] = 1,
    ACTIONS(150), 18,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_void,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_RBRACE,
  [1043] = 1,
    ACTIONS(152), 18,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_void,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_RBRACE,
  [1064] = 1,
    ACTIONS(154), 18,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_void,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_RBRACE,
  [1085] = 1,
    ACTIONS(156), 14,
      sym_comment,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_void,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_RBRACE,
  [1102] = 1,
    ACTIONS(158), 14,
      sym_comment,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_void,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_RBRACE,
  [1119] = 1,
    ACTIONS(160), 14,
      sym_comment,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_void,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_RBRACE,
  [1136] = 1,
    ACTIONS(162), 14,
      sym_comment,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_void,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_RBRACE,
  [1153] = 1,
    ACTIONS(164), 14,
      sym_comment,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_void,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_RBRACE,
  [1170] = 1,
    ACTIONS(166), 14,
      sym_comment,
      anon_sym_put,
      anon_sym_debug,
      anon_sym_trans,
      anon_sym_pers,
      anon_sym_sub,
      anon_sym_lab,
      anon_sym_jump,
      anon_sym_write,
      anon_sym_void,
      anon_sym_iter,
      anon_sym_enum,
      anon_sym_count,
      anon_sym_RBRACE,
  [1187] = 8,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    ACTIONS(170), 1,
      sym_seq_name,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    ACTIONS(176), 1,
      sym_iden,
    STATE(26), 1,
      sym_expr,
    ACTIONS(174), 2,
      sym_char_literal,
      sym_number,
    STATE(7), 2,
      sym_variable,
      sym_string,
    STATE(8), 2,
      sym_binary,
      sym_paran,
  [1215] = 8,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    ACTIONS(170), 1,
      sym_seq_name,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    ACTIONS(176), 1,
      sym_iden,
    STATE(28), 1,
      sym_expr,
    ACTIONS(174), 2,
      sym_char_literal,
      sym_number,
    STATE(7), 2,
      sym_variable,
      sym_string,
    STATE(8), 2,
      sym_binary,
      sym_paran,
  [1243] = 8,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    ACTIONS(170), 1,
      sym_seq_name,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    ACTIONS(176), 1,
      sym_iden,
    STATE(6), 1,
      sym_expr,
    ACTIONS(174), 2,
      sym_char_literal,
      sym_number,
    STATE(7), 2,
      sym_variable,
      sym_string,
    STATE(8), 2,
      sym_binary,
      sym_paran,
  [1271] = 8,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    ACTIONS(170), 1,
      sym_seq_name,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    ACTIONS(176), 1,
      sym_iden,
    STATE(29), 1,
      sym_expr,
    ACTIONS(174), 2,
      sym_char_literal,
      sym_number,
    STATE(7), 2,
      sym_variable,
      sym_string,
    STATE(8), 2,
      sym_binary,
      sym_paran,
  [1299] = 8,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    ACTIONS(170), 1,
      sym_seq_name,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    ACTIONS(176), 1,
      sym_iden,
    STATE(30), 1,
      sym_expr,
    ACTIONS(174), 2,
      sym_char_literal,
      sym_number,
    STATE(7), 2,
      sym_variable,
      sym_string,
    STATE(8), 2,
      sym_binary,
      sym_paran,
  [1327] = 8,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    ACTIONS(170), 1,
      sym_seq_name,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    ACTIONS(176), 1,
      sym_iden,
    STATE(17), 1,
      sym_expr,
    ACTIONS(174), 2,
      sym_char_literal,
      sym_number,
    STATE(7), 2,
      sym_variable,
      sym_string,
    STATE(8), 2,
      sym_binary,
      sym_paran,
  [1355] = 8,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    ACTIONS(170), 1,
      sym_seq_name,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    ACTIONS(176), 1,
      sym_iden,
    STATE(15), 1,
      sym_expr,
    ACTIONS(174), 2,
      sym_char_literal,
      sym_number,
    STATE(7), 2,
      sym_variable,
      sym_string,
    STATE(8), 2,
      sym_binary,
      sym_paran,
  [1383] = 8,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    ACTIONS(170), 1,
      sym_seq_name,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    ACTIONS(176), 1,
      sym_iden,
    STATE(11), 1,
      sym_expr,
    ACTIONS(174), 2,
      sym_char_literal,
      sym_number,
    STATE(7), 2,
      sym_variable,
      sym_string,
    STATE(8), 2,
      sym_binary,
      sym_paran,
  [1411] = 8,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    ACTIONS(170), 1,
      sym_seq_name,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    ACTIONS(176), 1,
      sym_iden,
    STATE(31), 1,
      sym_expr,
    ACTIONS(174), 2,
      sym_char_literal,
      sym_number,
    STATE(7), 2,
      sym_variable,
      sym_string,
    STATE(8), 2,
      sym_binary,
      sym_paran,
  [1439] = 8,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    ACTIONS(170), 1,
      sym_seq_name,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    ACTIONS(176), 1,
      sym_iden,
    STATE(16), 1,
      sym_expr,
    ACTIONS(174), 2,
      sym_char_literal,
      sym_number,
    STATE(7), 2,
      sym_variable,
      sym_string,
    STATE(8), 2,
      sym_binary,
      sym_paran,
  [1467] = 8,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    ACTIONS(170), 1,
      sym_seq_name,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    ACTIONS(176), 1,
      sym_iden,
    STATE(19), 1,
      sym_expr,
    ACTIONS(174), 2,
      sym_char_literal,
      sym_number,
    STATE(7), 2,
      sym_variable,
      sym_string,
    STATE(8), 2,
      sym_binary,
      sym_paran,
  [1495] = 8,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    ACTIONS(170), 1,
      sym_seq_name,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    ACTIONS(176), 1,
      sym_iden,
    STATE(27), 1,
      sym_expr,
    ACTIONS(174), 2,
      sym_char_literal,
      sym_number,
    STATE(7), 2,
      sym_variable,
      sym_string,
    STATE(8), 2,
      sym_binary,
      sym_paran,
  [1523] = 8,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    ACTIONS(170), 1,
      sym_seq_name,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    ACTIONS(176), 1,
      sym_iden,
    STATE(20), 1,
      sym_expr,
    ACTIONS(174), 2,
      sym_char_literal,
      sym_number,
    STATE(7), 2,
      sym_variable,
      sym_string,
    STATE(8), 2,
      sym_binary,
      sym_paran,
  [1551] = 8,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    ACTIONS(170), 1,
      sym_seq_name,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    ACTIONS(176), 1,
      sym_iden,
    STATE(18), 1,
      sym_expr,
    ACTIONS(174), 2,
      sym_char_literal,
      sym_number,
    STATE(7), 2,
      sym_variable,
      sym_string,
    STATE(8), 2,
      sym_binary,
      sym_paran,
  [1579] = 8,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    ACTIONS(170), 1,
      sym_seq_name,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    ACTIONS(176), 1,
      sym_iden,
    STATE(12), 1,
      sym_expr,
    ACTIONS(174), 2,
      sym_char_literal,
      sym_number,
    STATE(7), 2,
      sym_variable,
      sym_string,
    STATE(8), 2,
      sym_binary,
      sym_paran,
  [1607] = 8,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    ACTIONS(170), 1,
      sym_seq_name,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    ACTIONS(176), 1,
      sym_iden,
    STATE(21), 1,
      sym_expr,
    ACTIONS(174), 2,
      sym_char_literal,
      sym_number,
    STATE(7), 2,
      sym_variable,
      sym_string,
    STATE(8), 2,
      sym_binary,
      sym_paran,
  [1635] = 8,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    ACTIONS(170), 1,
      sym_seq_name,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    ACTIONS(176), 1,
      sym_iden,
    STATE(13), 1,
      sym_expr,
    ACTIONS(174), 2,
      sym_char_literal,
      sym_number,
    STATE(7), 2,
      sym_variable,
      sym_string,
    STATE(8), 2,
      sym_binary,
      sym_paran,
  [1663] = 8,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    ACTIONS(170), 1,
      sym_seq_name,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    ACTIONS(176), 1,
      sym_iden,
    STATE(22), 1,
      sym_expr,
    ACTIONS(174), 2,
      sym_char_literal,
      sym_number,
    STATE(7), 2,
      sym_variable,
      sym_string,
    STATE(8), 2,
      sym_binary,
      sym_paran,
  [1691] = 8,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    ACTIONS(170), 1,
      sym_seq_name,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    ACTIONS(176), 1,
      sym_iden,
    STATE(23), 1,
      sym_expr,
    ACTIONS(174), 2,
      sym_char_literal,
      sym_number,
    STATE(7), 2,
      sym_variable,
      sym_string,
    STATE(8), 2,
      sym_binary,
      sym_paran,
  [1719] = 8,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    ACTIONS(170), 1,
      sym_seq_name,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    ACTIONS(176), 1,
      sym_iden,
    STATE(24), 1,
      sym_expr,
    ACTIONS(174), 2,
      sym_char_literal,
      sym_number,
    STATE(7), 2,
      sym_variable,
      sym_string,
    STATE(8), 2,
      sym_binary,
      sym_paran,
  [1747] = 8,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    ACTIONS(170), 1,
      sym_seq_name,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    ACTIONS(176), 1,
      sym_iden,
    STATE(14), 1,
      sym_expr,
    ACTIONS(174), 2,
      sym_char_literal,
      sym_number,
    STATE(7), 2,
      sym_variable,
      sym_string,
    STATE(8), 2,
      sym_binary,
      sym_paran,
  [1775] = 8,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    ACTIONS(170), 1,
      sym_seq_name,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    ACTIONS(176), 1,
      sym_iden,
    STATE(25), 1,
      sym_expr,
    ACTIONS(174), 2,
      sym_char_literal,
      sym_number,
    STATE(7), 2,
      sym_variable,
      sym_string,
    STATE(8), 2,
      sym_binary,
      sym_paran,
  [1803] = 7,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_use,
    ACTIONS(9), 1,
      anon_sym_seq,
    ACTIONS(11), 1,
      anon_sym_rout,
    ACTIONS(178), 1,
      ts_builtin_sym_end,
    STATE(64), 2,
      sym_unit,
      aux_sym_source_file_repeat1,
    STATE(74), 3,
      sym_import,
      sym_sequence,
      sym_routine,
  [1828] = 7,
    ACTIONS(180), 1,
      ts_builtin_sym_end,
    ACTIONS(182), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_use,
    ACTIONS(188), 1,
      anon_sym_seq,
    ACTIONS(191), 1,
      anon_sym_rout,
    STATE(64), 2,
      sym_unit,
      aux_sym_source_file_repeat1,
    STATE(74), 3,
      sym_import,
      sym_sequence,
      sym_routine,
  [1853] = 2,
    ACTIONS(196), 2,
      sym_seq_name,
      sym_iden,
    ACTIONS(194), 4,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      sym_char_literal,
      sym_number,
  [1864] = 1,
    ACTIONS(198), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
  [1872] = 1,
    ACTIONS(200), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
  [1880] = 4,
    ACTIONS(202), 1,
      anon_sym_SQUOTE,
    ACTIONS(204), 1,
      sym_string_literal,
    ACTIONS(207), 1,
      anon_sym_LBRACE,
    STATE(68), 2,
      sym_string_format,
      aux_sym_string_content_repeat1,
  [1894] = 1,
    ACTIONS(210), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
  [1902] = 5,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    ACTIONS(212), 1,
      sym_iden,
    STATE(79), 1,
      sym_close_scope,
    STATE(82), 1,
      sym_seq_entry,
    STATE(88), 1,
      aux_sym_sequence_repeat1,
  [1918] = 5,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    ACTIONS(212), 1,
      sym_iden,
    STATE(69), 1,
      sym_close_scope,
    STATE(70), 1,
      aux_sym_sequence_repeat1,
    STATE(82), 1,
      sym_seq_entry,
  [1934] = 3,
    ACTIONS(214), 1,
      anon_sym_RPAREN,
    ACTIONS(216), 2,
      sym_key_in,
      sym_key_out,
    STATE(80), 2,
      sym_param_def,
      aux_sym_param_interface_repeat1,
  [1946] = 1,
    ACTIONS(218), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
  [1954] = 1,
    ACTIONS(220), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
  [1962] = 4,
    ACTIONS(222), 1,
      sym_string_literal,
    ACTIONS(224), 1,
      anon_sym_LBRACE,
    STATE(117), 1,
      sym_string_content,
    STATE(78), 2,
      sym_string_format,
      aux_sym_string_content_repeat1,
  [1976] = 5,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    ACTIONS(226), 1,
      anon_sym_LPAREN,
    STATE(3), 1,
      sym_open_scope,
    STATE(67), 1,
      sym_tree,
    STATE(95), 1,
      sym_param_interface,
  [1992] = 3,
    ACTIONS(228), 1,
      anon_sym_RPAREN,
    ACTIONS(216), 2,
      sym_key_in,
      sym_key_out,
    STATE(72), 2,
      sym_param_def,
      aux_sym_param_interface_repeat1,
  [2004] = 4,
    ACTIONS(224), 1,
      anon_sym_LBRACE,
    ACTIONS(230), 1,
      anon_sym_SQUOTE,
    ACTIONS(232), 1,
      sym_string_literal,
    STATE(68), 2,
      sym_string_format,
      aux_sym_string_content_repeat1,
  [2018] = 1,
    ACTIONS(234), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_use,
      anon_sym_seq,
      anon_sym_rout,
  [2026] = 3,
    ACTIONS(236), 1,
      anon_sym_RPAREN,
    ACTIONS(238), 2,
      sym_key_in,
      sym_key_out,
    STATE(80), 2,
      sym_param_def,
      aux_sym_param_interface_repeat1,
  [2038] = 1,
    ACTIONS(241), 4,
      sym_comment,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_iden,
  [2045] = 3,
    ACTIONS(243), 1,
      sym_comment,
    ACTIONS(245), 1,
      anon_sym_COMMA,
    ACTIONS(247), 2,
      anon_sym_RBRACE,
      sym_iden,
  [2056] = 4,
    ACTIONS(249), 1,
      anon_sym_RPAREN,
    ACTIONS(251), 1,
      sym_iden,
    STATE(87), 1,
      aux_sym_sub_repeat1,
    STATE(115), 1,
      sym_param_name,
  [2069] = 4,
    ACTIONS(253), 1,
      sym_eos,
    ACTIONS(255), 1,
      sym_bind,
    ACTIONS(257), 1,
      sym_iden,
    STATE(101), 1,
      sym_label,
  [2082] = 4,
    ACTIONS(259), 1,
      anon_sym_BQUOTE,
    ACTIONS(261), 1,
      sym_iden,
    STATE(112), 1,
      sym_string_format_content,
    STATE(116), 1,
      sym_variable,
  [2095] = 4,
    ACTIONS(251), 1,
      sym_iden,
    ACTIONS(263), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      aux_sym_sub_repeat1,
    STATE(115), 1,
      sym_param_name,
  [2108] = 4,
    ACTIONS(265), 1,
      anon_sym_RPAREN,
    ACTIONS(267), 1,
      sym_iden,
    STATE(87), 1,
      aux_sym_sub_repeat1,
    STATE(115), 1,
      sym_param_name,
  [2121] = 4,
    ACTIONS(270), 1,
      anon_sym_RBRACE,
    ACTIONS(272), 1,
      sym_iden,
    STATE(82), 1,
      sym_seq_entry,
    STATE(88), 1,
      aux_sym_sequence_repeat1,
  [2134] = 1,
    ACTIONS(275), 3,
      anon_sym_RPAREN,
      sym_key_in,
      sym_key_out,
  [2140] = 2,
    ACTIONS(279), 1,
      sym_string_literal,
    ACTIONS(277), 2,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
  [2148] = 3,
    ACTIONS(261), 1,
      sym_iden,
    STATE(116), 1,
      sym_variable,
    STATE(124), 1,
      sym_string_format_content,
  [2158] = 3,
    ACTIONS(257), 1,
      sym_iden,
    ACTIONS(281), 1,
      sym_eos,
    STATE(123), 1,
      sym_label,
  [2168] = 2,
    ACTIONS(285), 1,
      sym_string_literal,
    ACTIONS(283), 2,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
  [2176] = 2,
    ACTIONS(287), 1,
      sym_comment,
    ACTIONS(270), 2,
      anon_sym_RBRACE,
      sym_iden,
  [2184] = 3,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    STATE(3), 1,
      sym_open_scope,
    STATE(73), 1,
      sym_tree,
  [2194] = 2,
    ACTIONS(289), 1,
      sym_iden,
    STATE(122), 1,
      sym_rout_name,
  [2201] = 2,
    ACTIONS(251), 1,
      sym_iden,
    STATE(126), 1,
      sym_param_name,
  [2208] = 2,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    STATE(110), 1,
      sym_string,
  [2215] = 2,
    ACTIONS(291), 1,
      anon_sym_LBRACE,
    STATE(71), 1,
      sym_open_scope,
  [2222] = 1,
    ACTIONS(293), 2,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
  [2227] = 2,
    ACTIONS(295), 1,
      sym_eos,
    ACTIONS(297), 1,
      sym_bind,
  [2234] = 1,
    ACTIONS(299), 2,
      anon_sym_RBRACE,
      sym_iden,
  [2239] = 2,
    ACTIONS(289), 1,
      sym_iden,
    STATE(76), 1,
      sym_rout_name,
  [2246] = 1,
    ACTIONS(301), 2,
      anon_sym_RPAREN,
      sym_iden,
  [2251] = 2,
    ACTIONS(261), 1,
      sym_iden,
    STATE(125), 1,
      sym_variable,
  [2258] = 1,
    ACTIONS(166), 2,
      anon_sym_RBRACE,
      sym_iden,
  [2263] = 1,
    ACTIONS(270), 2,
      anon_sym_RBRACE,
      sym_iden,
  [2268] = 1,
    ACTIONS(303), 2,
      sym_eos,
      sym_bind,
  [2273] = 1,
    ACTIONS(305), 2,
      sym_eos,
      sym_bind,
  [2278] = 1,
    ACTIONS(307), 1,
      sym_eos,
  [2282] = 1,
    ACTIONS(309), 1,
      ts_builtin_sym_end,
  [2286] = 1,
    ACTIONS(311), 1,
      anon_sym_RBRACE,
  [2290] = 1,
    ACTIONS(313), 1,
      anon_sym_LBRACE,
  [2294] = 1,
    ACTIONS(315), 1,
      sym_eos,
  [2298] = 1,
    ACTIONS(317), 1,
      sym_bind,
  [2302] = 1,
    ACTIONS(319), 1,
      anon_sym_DOT,
  [2306] = 1,
    ACTIONS(321), 1,
      anon_sym_SQUOTE,
  [2310] = 1,
    ACTIONS(323), 1,
      sym_eos,
  [2314] = 1,
    ACTIONS(325), 1,
      anon_sym_LBRACE,
  [2318] = 1,
    ACTIONS(327), 1,
      sym_seq_name,
  [2322] = 1,
    ACTIONS(329), 1,
      sym_eos,
  [2326] = 1,
    ACTIONS(331), 1,
      anon_sym_LPAREN,
  [2330] = 1,
    ACTIONS(333), 1,
      sym_eos,
  [2334] = 1,
    ACTIONS(335), 1,
      anon_sym_RBRACE,
  [2338] = 1,
    ACTIONS(337), 1,
      anon_sym_RBRACE,
  [2342] = 1,
    ACTIONS(339), 1,
      sym_eos,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 66,
  [SMALL_STATE(4)] = 132,
  [SMALL_STATE(5)] = 195,
  [SMALL_STATE(6)] = 228,
  [SMALL_STATE(7)] = 263,
  [SMALL_STATE(8)] = 295,
  [SMALL_STATE(9)] = 327,
  [SMALL_STATE(10)] = 359,
  [SMALL_STATE(11)] = 391,
  [SMALL_STATE(12)] = 426,
  [SMALL_STATE(13)] = 459,
  [SMALL_STATE(14)] = 494,
  [SMALL_STATE(15)] = 529,
  [SMALL_STATE(16)] = 558,
  [SMALL_STATE(17)] = 587,
  [SMALL_STATE(18)] = 616,
  [SMALL_STATE(19)] = 645,
  [SMALL_STATE(20)] = 674,
  [SMALL_STATE(21)] = 703,
  [SMALL_STATE(22)] = 732,
  [SMALL_STATE(23)] = 761,
  [SMALL_STATE(24)] = 790,
  [SMALL_STATE(25)] = 819,
  [SMALL_STATE(26)] = 848,
  [SMALL_STATE(27)] = 877,
  [SMALL_STATE(28)] = 906,
  [SMALL_STATE(29)] = 935,
  [SMALL_STATE(30)] = 964,
  [SMALL_STATE(31)] = 993,
  [SMALL_STATE(32)] = 1022,
  [SMALL_STATE(33)] = 1043,
  [SMALL_STATE(34)] = 1064,
  [SMALL_STATE(35)] = 1085,
  [SMALL_STATE(36)] = 1102,
  [SMALL_STATE(37)] = 1119,
  [SMALL_STATE(38)] = 1136,
  [SMALL_STATE(39)] = 1153,
  [SMALL_STATE(40)] = 1170,
  [SMALL_STATE(41)] = 1187,
  [SMALL_STATE(42)] = 1215,
  [SMALL_STATE(43)] = 1243,
  [SMALL_STATE(44)] = 1271,
  [SMALL_STATE(45)] = 1299,
  [SMALL_STATE(46)] = 1327,
  [SMALL_STATE(47)] = 1355,
  [SMALL_STATE(48)] = 1383,
  [SMALL_STATE(49)] = 1411,
  [SMALL_STATE(50)] = 1439,
  [SMALL_STATE(51)] = 1467,
  [SMALL_STATE(52)] = 1495,
  [SMALL_STATE(53)] = 1523,
  [SMALL_STATE(54)] = 1551,
  [SMALL_STATE(55)] = 1579,
  [SMALL_STATE(56)] = 1607,
  [SMALL_STATE(57)] = 1635,
  [SMALL_STATE(58)] = 1663,
  [SMALL_STATE(59)] = 1691,
  [SMALL_STATE(60)] = 1719,
  [SMALL_STATE(61)] = 1747,
  [SMALL_STATE(62)] = 1775,
  [SMALL_STATE(63)] = 1803,
  [SMALL_STATE(64)] = 1828,
  [SMALL_STATE(65)] = 1853,
  [SMALL_STATE(66)] = 1864,
  [SMALL_STATE(67)] = 1872,
  [SMALL_STATE(68)] = 1880,
  [SMALL_STATE(69)] = 1894,
  [SMALL_STATE(70)] = 1902,
  [SMALL_STATE(71)] = 1918,
  [SMALL_STATE(72)] = 1934,
  [SMALL_STATE(73)] = 1946,
  [SMALL_STATE(74)] = 1954,
  [SMALL_STATE(75)] = 1962,
  [SMALL_STATE(76)] = 1976,
  [SMALL_STATE(77)] = 1992,
  [SMALL_STATE(78)] = 2004,
  [SMALL_STATE(79)] = 2018,
  [SMALL_STATE(80)] = 2026,
  [SMALL_STATE(81)] = 2038,
  [SMALL_STATE(82)] = 2045,
  [SMALL_STATE(83)] = 2056,
  [SMALL_STATE(84)] = 2069,
  [SMALL_STATE(85)] = 2082,
  [SMALL_STATE(86)] = 2095,
  [SMALL_STATE(87)] = 2108,
  [SMALL_STATE(88)] = 2121,
  [SMALL_STATE(89)] = 2134,
  [SMALL_STATE(90)] = 2140,
  [SMALL_STATE(91)] = 2148,
  [SMALL_STATE(92)] = 2158,
  [SMALL_STATE(93)] = 2168,
  [SMALL_STATE(94)] = 2176,
  [SMALL_STATE(95)] = 2184,
  [SMALL_STATE(96)] = 2194,
  [SMALL_STATE(97)] = 2201,
  [SMALL_STATE(98)] = 2208,
  [SMALL_STATE(99)] = 2215,
  [SMALL_STATE(100)] = 2222,
  [SMALL_STATE(101)] = 2227,
  [SMALL_STATE(102)] = 2234,
  [SMALL_STATE(103)] = 2239,
  [SMALL_STATE(104)] = 2246,
  [SMALL_STATE(105)] = 2251,
  [SMALL_STATE(106)] = 2258,
  [SMALL_STATE(107)] = 2263,
  [SMALL_STATE(108)] = 2268,
  [SMALL_STATE(109)] = 2273,
  [SMALL_STATE(110)] = 2278,
  [SMALL_STATE(111)] = 2282,
  [SMALL_STATE(112)] = 2286,
  [SMALL_STATE(113)] = 2290,
  [SMALL_STATE(114)] = 2294,
  [SMALL_STATE(115)] = 2298,
  [SMALL_STATE(116)] = 2302,
  [SMALL_STATE(117)] = 2306,
  [SMALL_STATE(118)] = 2310,
  [SMALL_STATE(119)] = 2314,
  [SMALL_STATE(120)] = 2318,
  [SMALL_STATE(121)] = 2322,
  [SMALL_STATE(122)] = 2326,
  [SMALL_STATE(123)] = 2330,
  [SMALL_STATE(124)] = 2334,
  [SMALL_STATE(125)] = 2338,
  [SMALL_STATE(126)] = 2342,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(35),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(46),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(54),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(51),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(53),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(96),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(92),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(84),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(56),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(58),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(59),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(60),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2), SHIFT_REPEAT(62),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tree_repeat1, 2),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 1),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary, 3, .production_id = 2),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary, 3, .production_id = 2),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, .production_id = 1),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1, .production_id = 1),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paran, 3),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paran, 3),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sub_repeat1, 3),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 4),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_debug, 2),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_write, 2),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_void, 2),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 3),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_put, 4),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trans, 4),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pers, 4),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tree, 2),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_close_scope, 1),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tree, 3),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_iter, 5),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 7),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_count, 7),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_open_scope, 1),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(74),
  [185] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(98),
  [188] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(120),
  [191] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(103),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_op, 1),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_op, 1),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 3),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_routine, 3),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_content_repeat1, 2),
  [204] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_content_repeat1, 2), SHIFT_REPEAT(68),
  [207] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_content_repeat1, 2), SHIFT_REPEAT(85),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence, 4),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_routine, 4),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit, 1),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [224] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_content, 1),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence, 5),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_param_interface_repeat1, 2),
  [238] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_param_interface_repeat1, 2), SHIFT_REPEAT(97),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_seq_entry, 1),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 1),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 1),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sub_repeat1, 2),
  [267] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sub_repeat1, 2), SHIFT_REPEAT(109),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2),
  [272] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2), SHIFT_REPEAT(81),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_def, 3),
  [277] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_format, 4),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_format, 4),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lab, 1),
  [283] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_format, 3),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_format, 3),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rout_name, 1),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 2),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 3),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sub_repeat1, 4),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 1),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_name, 1),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [309] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_interface, 2),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub, 4),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_interface, 3),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub, 5),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [333] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lab, 2),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_format_content, 3),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_snug(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
